"""Tests for coord/test_report.py (#1436) — the pytest/cargo failure parsers
extracted from scripts/coord-test-runner.sh's grep/awk one-liners.

Fixtures under tests/fixtures/test_report/ are CAPTURED REAL OUTPUT, not
hand-written strings shaped to look like pytest/cargo output — each is
generated by actually running pytest or cargo test against a small scratch
project and saving stdout+stderr verbatim (no ANSI color, since output was
piped rather than attached to a tty). How each was produced:

- pytest_mixed_failures.txt: `pytest -q --tb=short` against a 4-test module
  with one genuine assertion failure and a `@pytest.mark.parametrize` test
  with a space embedded in the id (`"a b"`, `"c d"`) — the live
  awk-truncation bug case — plus one passing test and one test whose body
  prints "ERROR: ..." but itself passes (doesn't surface in FAILED output).
- pytest_collection_error.txt: `pytest -q --tb=short` against a module with
  a top-level `import this_module_does_not_exist_anywhere`.
- pytest_internal_error.txt: `pytest -q --tb=short` with a conftest.py hook
  (`pytest_collectstart`) that raises, crashing pytest itself.
- pytest_error_string_in_body.txt: `pytest -q --tb=short -rA` against a test
  that fails a genuine assertion AND prints "ERROR: ..." to stdout — the
  printed line survives verbatim in the "Captured stdout call" section.
- pytest_error_log_record.txt: `pytest -q --tb=short -rA` against a test that
  fails a genuine assertion AND emits a `logging` record at ERROR level — the
  record lands in "Captured log call" rendered at column 0 as
  `ERROR    <logger>:<file>:<line> <msg>` (the level name is `%(levelname)-8s`),
  which is the #3470 false positive: one ordinary failure that read as a
  collection error.
- pytest_no_parseable_failures.txt: `pytest -u -q --tb=short` against a test
  that calls `os._exit(1)` — the process dies before pytest's terminal
  reporter flushes anything, producing a genuinely empty file with exit 1.
- cargo_multi_target_failures.txt: `cargo test --no-fail-fast` in a 2-target
  crate (lib with 2 failing + 1 passing test, nested under `mod tests`, and
  a `tests/integration.rs` with 1 failing + 1 passing top-level test, no
  enclosing module) — captures both the "failures:" block appearing twice
  per target (list + summary) and a top-level (no "::") failing test name.
- cargo_compile_error.txt: `cargo test` against a crate with a type error
  (`i32 + &str`).
- cargo_no_parseable_failures.txt: `cargo test` against a crate whose single
  test calls `std::process::abort()` (SIGABRT) — no "failures:" block is
  ever printed.

Regenerate by re-running the commands above against equivalent scratch
projects; nothing here depends on a live worktree or the coordinator's own
suite.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from coord import test_report as tr

FIXTURES = Path(__file__).parent / "fixtures" / "test_report"


def _read(name: str) -> str:
    return (FIXTURES / name).read_text()


# ── pytest_failed_node_ids ──────────────────────────────────────────────────


def test_pytest_failed_node_ids_extracts_full_node_ids():
    ids = tr.pytest_failed_node_ids(_read("pytest_mixed_failures.txt"))
    assert ids == [
        "test_sample_failure.py::test_genuine_failure",
        "test_sample_failure.py::test_parametrized_with_spaces[a b]",
        "test_sample_failure.py::test_parametrized_with_spaces[c d]",
    ]


def test_pytest_failed_node_ids_does_not_truncate_parametrized_ids_with_spaces():
    # This is the live bug: `awk '{print $2}'` splits on whitespace, so
    # `FAILED test_sample_failure.py::test_parametrized_with_spaces[a b] - ...`
    # yields `test_sample_failure.py::test_parametrized_with_spaces[a` under
    # the shell implementation. The node id must survive whole, including
    # the space and closing bracket.
    ids = tr.pytest_failed_node_ids(_read("pytest_mixed_failures.txt"))
    assert "test_sample_failure.py::test_parametrized_with_spaces[a b]" in ids
    assert not any(node_id.endswith("[a") for node_id in ids)


def test_pytest_failed_node_ids_dedupes_and_sorts():
    doubled = _read("pytest_mixed_failures.txt") * 2
    ids = tr.pytest_failed_node_ids(doubled)
    assert ids == sorted(set(ids))
    assert len(ids) == 3


def test_pytest_failed_node_ids_empty_when_no_failed_lines():
    assert tr.pytest_failed_node_ids(_read("pytest_no_parseable_failures.txt")) == []
    assert tr.pytest_failed_node_ids(_read("pytest_collection_error.txt")) == []


def test_pytest_failed_node_ids_still_found_when_error_string_in_body():
    # The failing test's node id must still be picked up even though the
    # test body also printed a line starting with "ERROR".
    ids = tr.pytest_failed_node_ids(_read("pytest_error_string_in_body.txt"))
    assert ids == ["test_error_print.py::test_fails_and_prints_error"]


# ── pytest_has_collection_error ─────────────────────────────────────────────


def test_pytest_collection_error_detected_on_import_error():
    assert tr.pytest_has_collection_error(_read("pytest_collection_error.txt")) is True


def test_pytest_collection_error_detected_on_internalerror():
    assert tr.pytest_has_collection_error(_read("pytest_internal_error.txt")) is True


def test_pytest_collection_error_not_tripped_by_normal_failures():
    assert tr.pytest_has_collection_error(_read("pytest_mixed_failures.txt")) is False


def test_pytest_collection_error_not_tripped_by_error_string_in_test_body():
    # Sharp case from the issue: a test whose *body* prints "ERROR" at
    # line-start (it lands verbatim in "Captured stdout call") must not be
    # mistaken for a genuine collection/import error.
    assert tr.pytest_has_collection_error(_read("pytest_error_string_in_body.txt")) is False


def test_pytest_collection_error_not_tripped_by_captured_error_log_record():
    # #3470: the shape that actually broke a Test leg. pytest's "Captured log
    # call" section renders each record at COLUMN 0 with the level name padded
    # to eight characters — "ERROR    coord.agent_update:…" — so every suite
    # containing a test that exercises an error path and logs it looked like a
    # collection error to `grep -qE "^(ERROR|INTERNALERROR)"`. This is the
    # single ordinary failure underneath: the parser must see it as such.
    output = _read("pytest_error_log_record.txt")
    # The fixture really does contain a column-0 "ERROR" line — without this
    # the two assertions below would pass vacuously on any output at all.
    assert any(line.startswith("ERROR") for line in output.splitlines())
    assert tr.pytest_has_collection_error(output) is False
    assert tr.pytest_failed_node_ids(output) == [
        "test_error_log.py::test_fails_after_logging_an_error"
    ]


def test_pytest_collection_error_not_tripped_by_empty_output():
    assert tr.pytest_has_collection_error(_read("pytest_no_parseable_failures.txt")) is False


# ── cargo_failed_test_names ──────────────────────────────────────────────────


def test_cargo_failed_test_names_spans_multiple_targets():
    # Two "failures:"/"test result:" blocks (one per target: lib, then the
    # tests/integration.rs binary) must not bleed into each other or get
    # concatenated — every genuine failure from both targets is present.
    names = tr.cargo_failed_test_names(_read("cargo_multi_target_failures.txt"))
    assert names == [
        "integration_genuine_failure",
        "tests::lib_another_failure",
        "tests::lib_genuine_failure",
    ]


def test_cargo_failed_test_names_includes_names_without_module_path():
    # Live bug vs. the shell's `/^    [a-zA-Z_]+::/` pattern: it requires
    # "::" and so drops a top-level `#[test]` with no enclosing `mod` (the
    # shape of tui/tests/acceptance.rs). "integration_genuine_failure" has
    # no "::" and must still be captured.
    names = tr.cargo_failed_test_names(_read("cargo_multi_target_failures.txt"))
    assert "integration_genuine_failure" in names


def test_cargo_failed_test_names_dedupes_within_each_targets_double_listing():
    # Within one target, cargo prints the failures block TWICE (interleaved
    # per-test stdout dump, then the final summary list) — `sort -u`
    # idempotence must hold per name, not just per whole block.
    names = tr.cargo_failed_test_names(_read("cargo_multi_target_failures.txt"))
    assert names.count("tests::lib_another_failure") == 1
    assert names.count("tests::lib_genuine_failure") == 1


def test_cargo_failed_test_names_sorted():
    names = tr.cargo_failed_test_names(_read("cargo_multi_target_failures.txt"))
    assert names == sorted(names)


def test_cargo_failed_test_names_empty_on_compile_error():
    assert tr.cargo_failed_test_names(_read("cargo_compile_error.txt")) == []


def test_cargo_failed_test_names_empty_when_no_failures_block():
    # Non-zero exit (SIGABRT) with no "failures:" block at all is its own
    # outcome, distinct from "zero failures" (which only happens on a clean
    # exit 0) — the caller (coord-test-runner.sh / #1392) must not collapse
    # "could not parse anything" into a pass. This function's contract is
    # simply: no block found → empty list, never a guess.
    assert tr.cargo_failed_test_names(_read("cargo_no_parseable_failures.txt")) == []


# ── cargo_has_compile_error ──────────────────────────────────────────────────


def test_cargo_compile_error_detected():
    assert tr.cargo_has_compile_error(_read("cargo_compile_error.txt")) is True


def test_cargo_compile_error_not_tripped_by_genuine_test_failures():
    # Regression test for a live bug found while extracting this: cargo
    # prints "error: test failed, to rerun pass `--lib`" / "error: N targets
    # failed:" on ANY nonzero-exit test run, compile error or not. A literal
    # translation of the shell's `^error(\[E[0-9]+\])?:` alternative would
    # match that generic wrapper line and misclassify every ordinary test
    # failure as a compile error.
    assert tr.cargo_has_compile_error(_read("cargo_multi_target_failures.txt")) is False


def test_cargo_compile_error_not_tripped_by_process_abort():
    # Same generic "error: test failed, to rerun pass ..." wrapper appears
    # here too (SIGABRT, no failures: block) — must not be misread as a
    # compile error either; it's the distinct "no parseable failures" case.
    assert tr.cargo_has_compile_error(_read("cargo_no_parseable_failures.txt")) is False


@pytest.mark.parametrize(
    "fixture",
    ["pytest_mixed_failures.txt", "pytest_collection_error.txt"],
)
def test_cargo_functions_are_inert_on_pytest_output(fixture):
    # Sanity: the cargo parsers shouldn't accidentally match pytest's very
    # differently-shaped output.
    text = _read(fixture)
    assert tr.cargo_failed_test_names(text) == []
    assert tr.cargo_has_compile_error(text) is False
