"""``tui-pty`` acceptance driver — Tier 2, real terminal (#3483).

Every black-box driver ``coord`` runs before this one drives the app
**in-process** (``tui-tuidriver`` goes through quadraui's ``TuiDriver``, a
Rust in-memory harness — see CLAUDE.md's coord-tui section). On 2026-09-29,
three real Windows TUI bugs all passed their in-process tests: a ~1 Hz
foreground flicker (vimcode#1634), activity-bar clicks doing nothing
(vimcode#1636), and slow right-click menus (vimcode#1635). The bytes an
in-process harness feeds the app are never generated by a real terminal, and
the bytes it reads back never pass through one either — so a whole class of
bug (idle repaint churn, real input translation, real paint latency) is
invisible to it by construction.

This module is that missing tier: it launches the repo's **real compiled
binary** under a **real pseudo-terminal** — a Unix ``pty`` via the stdlib
:mod:`pty` module on Linux/macOS (:class:`UnixPtyChild`), **ConPTY** on
Windows via the optional ``pywinpty`` package, the ``tui-pty`` extra's
Windows-only dependency (:class:`WindowsConPtyChild`) — sends real terminal
byte sequences (keys, SGR mouse including right-button and wheel), records
the raw output byte stream with timestamps, and feeds it through a VT
emulator (`pyte`, the ``tui-pty`` extra's cross-platform dependency) so
assertions can read the resulting screen grid (cell text and SGR
attributes).

**Smoke spec.** :func:`parse_smoke_spec` reads a platform-neutral YAML file,
checked into the *driven* repo (one file per app — the ``tui-pty`` analogue
of ``tui-tuidriver``'s ``tui/tests/acceptance.rs`` entrypoint; see
:func:`coord.acceptance_drivers._run_tui_pty`'s docstring for how its path
is threaded through as the driver's ``entrypoint:``). Steps:

- ``launch`` — spawn the real binary under the pty/ConPTY.
- ``key: <name>`` — send one key, or a space-separated chord sequence
  (``ctrl+k ctrl+w``). Parsed under the grammar shared by all four drivers
  (:mod:`coord.key_spec`, #3639): any combination of
  ``ctrl``/``alt``/``shift`` modifiers (``cmd``/``super``/``meta`` parse but
  always raise :class:`~coord.key_spec.UnsupportedKey` here — terminals have
  no such key), a named key (``enter``, ``esc``, ``tab``, ``backspace``,
  ``delete``, ``insert``, ``space``, arrow keys, ``home``/``end``,
  ``pageup``/``pagedown``, ``f1``-``f24``) or any single printable
  character, including punctuation — see :func:`encode_key`/
  :func:`encode_key_sequence` for exactly how each is encoded.
- ``click: {row, col, button}`` — an SGR mouse click at 0-indexed
  ``(row, col)``; ``button`` is ``left`` (default), ``middle``, ``right``, or
  ``wheel-up``/``wheel-down`` (single-shot, no release event — mirrors a
  real wheel).
- ``drag: {row, col, to_row, to_col, button}`` (#3604) — a press at
  0-indexed ``(row, col)``, one SGR motion event at ``(to_row, to_col)``
  with the button-held bit set, then a release there; ``button`` is
  ``left`` (default)/``middle``/``right`` (no wheel — a wheel has no
  "held" state to drag with). See :func:`encode_drag`.
- ``resize: {cols, rows}`` (#3604) — live-resize the pty/ConPTY itself to
  *cols* x *rows* (``TIOCSWINSZ`` on Unix, ``PtyProcess.setwinsize`` on
  Windows) and resize the VT screen the same way, so a reflow step can run
  mid-spec rather than only at ``launch``. See :meth:`SmokeRunner._do_resize`.
- ``wait_idle: {ms, timeout_ms}`` — block until the byte stream has been
  quiet for ``ms`` milliseconds, or fail after ``timeout_ms`` without ever
  reaching that quiet window (default 5000ms) — a precondition step, not an
  assertion on its own, but still fails the run if the app never settles.
- ``expect_screen: {region, text, attr}`` — the current VT screen (or a
  ``region: {row, col, width, height}`` sub-rectangle) must contain ``text``
  (a plain substring check against the rendered lines) and/or match
  ``attr: {row, col, <pyte Char field>: <expected value>}`` for one cell
  (e.g. ``{row: 3, col: 5, bold: true}``). At least one of ``text``/``attr``
  is required — a step with neither has nothing to assert against and
  could never fail, which :func:`parse_smoke_spec` rejects (#2096). The
  ``attr`` mapping must additionally name at least one attribute key
  *besides* ``row``/``col``: those two only address the cell, so an
  ``attr: {row: 3, col: 5}`` is just as unfalsifiable and is rejected too.
- ``expect_silent: {seconds}`` — the byte stream must receive **zero**
  bytes over a full ``seconds``-long real-time window. This is vimcode#1634's
  regression check: an idle app that's actually idle produces no repaint
  traffic; a ~1 Hz flicker does. See :meth:`SmokeRunner._do_expect_silent`
  for why this can only be answered by actually waiting out the window and
  re-reading a byte counter afterward, never by the mere absence of an
  exception (#2096: unconfirmed success is a defect).
- ``expect_within: {ms, text, region}`` — ``text`` must appear on the (VT)
  screen within ``ms`` milliseconds of this step starting; polls the live
  screen repeatedly rather than sampling once, so a slow-but-eventual paint
  still passes and a truly-never-appears one genuinely fails at the
  deadline (vimcode#1635's right-click-menu-latency regression check).
- ``type_text: {text}`` (#3650) — writes *text* straight to the pty's own
  stdin fd (:meth:`PtyChild.write`), the SAME real-OS path every other
  action step already uses — never into the app's in-memory input buffer.
  Unlike ``key:`` (which goes through the terminal-byte-encoding grammar,
  :mod:`coord.key_spec`), this sends the literal UTF-8 bytes of *text*
  as-is: the workhorse for "type a filename/search string/command line",
  where a spec author wants exactly these characters delivered, not a named
  key or chord.
- ``expect_file: {path, timeout_ms, contains}`` (#3650) — *path* must exist
  within *timeout_ms* (default 5000), optionally containing the substring
  *contains*. The one new step with no terminal-specific behaviour at all —
  see :mod:`coord.native_fs_wait`, the single shared implementation every
  Tier-2 native driver calls through (#2096 "one question, one answer").
  *path* may use ``$VAR``/``~`` (or the PowerShell ``$env:VAR`` spelling);
  it's resolved in THIS process, against this process's own environment —
  not the pty child's. The common case is both run on the same host (this
  driver has no remotely-bridged child), so the two environments are
  usually identical in practice, but a spec relying on a variable this
  process doesn't itself have set will not see it.

**The ``ESC[6n`` cursor-position query lesson (vimcode's own ConPTY tests,
folded in before this issue was dispatched).** ratatui's ``Terminal::new()``
blocks at startup on a Device Status Report reply to the ``ESC[6n`` it
sends — a real terminal answers this "where's the cursor" query
transparently; a driver standing in for one must too, or the app never
paints anything and every subsequent step times out waiting on a blank
screen. **On real Windows ConPTY, answering synchronously from inside the
byte-stream reader callback deadlocks the session** (verified by vimcode's
own ``tests/conpty_idle_flicker.rs``/``tests/conpty_activity_bar_click.rs`,
built with ``portable_pty`` + a ``vt100`` parser for exactly this tier).
:class:`SmokeRunner` therefore splits reading and replying across two
threads: ``_reader_loop`` only reads bytes, feeds the VT screen, and — on
spotting ``ESC[6n`` — enqueues a reply; a separate ``_responder_loop``
dequeues and writes it. Never write the child's stdin from the reader
thread itself.

**What this tier does NOT see** (spelled out in the issue, and important —
see vimcode#3484 for the tier this hands off to): raw ConPTY was not the
last mile for any of the three Windows bugs above. All three *passed* under
a raw ConPTY too — the idle byte stream is genuinely silent (#1634), a
right-click paints in about 50µs measured this way (#1635), activity-bar
clicks work (#1636) — yet the operator still saw flicker, lag and dead
clicks in a real terminal *window*. This driver proves the app's own
behaviour is correct against a real pty; it cannot see a terminal
emulator's own rendering/input-translation behaviour (Windows Terminal,
legacy conhost, iTerm, GNOME Terminal) — that needs a native kind driving
and capturing an actual terminal window (vimcode#3484).
"""

from __future__ import annotations

import os
import queue
import signal
import subprocess
import sys
import threading
import time
from dataclasses import dataclass
from typing import Callable, Protocol

import yaml

from coord.key_spec import KeyChord, KeySpecError, UnsupportedKey, parse_key_spec
from coord.native_fs_wait import wait_for_file
from coord.shell_exec_wrap import wrap_launch_command as _wrap_launch_command


class TuiPtySpecError(Exception):
    """Raised for a malformed smoke spec: invalid YAML, a missing/empty
    ``steps:`` list, an unknown step ``type``, a missing required field, or
    an unrecognized key/button name."""


class TuiPtyRuntimeError(Exception):
    """Raised when the pty/ConPTY child itself can't be spawned or driven:
    missing platform support, a missing optional dependency (the
    ``tui-pty`` extra), the child process dying unexpectedly, or a
    ``wait_idle`` step that never sees the stream go quiet."""


# ── smoke spec model ────────────────────────────────────────────────────────

_REQUIRED_FIELDS: dict[str, tuple[str, ...]] = {
    "launch": (),
    "key": ("key",),
    "click": ("row", "col"),
    "drag": ("row", "col", "to_row", "to_col"),
    "resize": ("cols", "rows"),
    "wait_idle": (),
    "expect_screen": (),
    "expect_silent": (),
    "expect_within": ("text",),
    # #3650: typed through the real pty itself (`SmokeRunner._do_type_text`
    # writes straight to the child's stdin fd) — never injected into the
    # app's own in-memory buffer, or a vimcode#1825-class "keystrokes went
    # to the launching terminal instead" bug would stay invisible here too.
    "type_text": ("text",),
    # #3650: a pure filesystem check — see `coord.native_fs_wait`'s own
    # docstring for why this is the one shared implementation every driver
    # calls, not a tui-pty-specific one.
    "expect_file": ("path",),
}

_VALID_BUTTONS = ("left", "middle", "right", "wheel-up", "wheel-down")
#: #3604: a drag has no "release" concept for a wheel notch, so it's
#: restricted to the buttons that genuinely support press-hold-release.
_DRAG_BUTTONS = ("left", "middle", "right")


@dataclass(frozen=True)
class SmokeStep:
    """One parsed step of a smoke spec.

    ``kind`` selects the step type; every field this step type doesn't use
    keeps its default so callers never have to branch on ``kind`` before
    reading one.
    """

    kind: str
    index: int
    id: str = ""
    key: str = ""
    row: int = 0
    col: int = 0
    to_row: int = 0
    to_col: int = 0
    button: str = "left"
    ms: int = 200
    timeout_ms: int = 5000
    seconds: float = 1.0
    text: str = ""
    region: dict | None = None
    attr: dict | None = None
    cols: int = 0
    rows: int = 0
    path: str = ""
    contains: str = ""

    @property
    def step_id(self) -> str:
        """The normalized ``tests[].id`` this step reports under — the
        spec author's own ``id:`` when given (so a named regression, e.g.
        vimcode#1634's ``idle-flicker-1634``, stays a stable id across
        unrelated spec edits), else a positional fallback."""
        return self.id or f"{self.index:03d} {self.kind}"


@dataclass(frozen=True)
class SmokeSpec:
    name: str
    cols: int
    rows: int
    steps: tuple[SmokeStep, ...]


def _int_default(value, default: int) -> int:
    """``int(value)``, falling back to *default* only when *value* is
    absent (``None``) — unlike the ``int(value or default)`` idiom, an
    explicit literal ``0`` in the YAML is honored rather than silently
    treated as "absent"."""
    return default if value is None else int(value)


def _float_default(value, default: float) -> float:
    """The :func:`_int_default` idiom for a ``float`` field."""
    return default if value is None else float(value)


def parse_smoke_spec(yaml_text: str) -> SmokeSpec:
    """Parse a platform-neutral smoke-spec YAML document into a
    :class:`SmokeSpec`.

    Top level: ``name:`` (optional, defaults to ``""``), ``cols:``/``rows:``
    (optional, default 80x24), ``steps:`` — a non-empty list of mappings,
    each carrying a ``type:`` naming one of :data:`_REQUIRED_FIELDS`'s keys
    plus that type's own fields.

    Raises :class:`TuiPtySpecError` — never returns a partially-parsed
    spec — for: invalid YAML, a non-mapping document, a missing/empty/
    non-list ``steps:``, a step that isn't a mapping, an unknown ``type:``,
    a step missing one of its type's required fields, an ``expect_within``
    with an empty ``text:``, an ``expect_screen`` with neither ``text:``
    nor ``attr:`` (it would have nothing to assert and could never fail),
    an ``expect_screen`` whose ``attr:`` holds only the cell-addressing
    ``row:``/``col:`` keys and so is equally unfalsifiable, or a
    ``click``/``expect_screen`` (via ``attr:``) naming an unrecognized
    ``button:``.
    """
    try:
        raw = yaml.safe_load(yaml_text)
    except yaml.YAMLError as e:
        raise TuiPtySpecError(f"smoke spec is not valid YAML: {e}") from e

    if not isinstance(raw, dict):
        raise TuiPtySpecError("smoke spec must be a YAML mapping at the top level")

    steps_raw = raw.get("steps")
    if not isinstance(steps_raw, list) or not steps_raw:
        raise TuiPtySpecError("smoke spec must have a non-empty 'steps:' list")

    steps: list[SmokeStep] = []
    for i, entry in enumerate(steps_raw):
        if not isinstance(entry, dict):
            raise TuiPtySpecError(f"steps[{i}] must be a mapping")
        kind = entry.get("type")
        if kind not in _REQUIRED_FIELDS:
            raise TuiPtySpecError(
                f"steps[{i}]: unknown step type {kind!r} — expected one of "
                f"{', '.join(sorted(_REQUIRED_FIELDS))}"
            )
        missing = [f for f in _REQUIRED_FIELDS[kind] if entry.get(f) in (None, "")]
        if missing:
            raise TuiPtySpecError(
                f"steps[{i}] (type={kind!r}) is missing required field(s): "
                f"{', '.join(missing)}"
            )
        button = str(entry.get("button", "left"))
        if kind == "click" and button not in _VALID_BUTTONS:
            raise TuiPtySpecError(
                f"steps[{i}]: unrecognized button {button!r} — expected one "
                f"of {', '.join(_VALID_BUTTONS)}"
            )
        if kind == "drag" and button not in _DRAG_BUTTONS:
            raise TuiPtySpecError(
                f"steps[{i}]: unrecognized drag button {button!r} — "
                f"expected one of {', '.join(_DRAG_BUTTONS)} (a wheel has "
                f"no held state to drag with)"
            )
        region = entry.get("region")
        if region is not None and not isinstance(region, dict):
            raise TuiPtySpecError(f"steps[{i}].region must be a mapping")
        attr = entry.get("attr")
        if attr is not None and not isinstance(attr, dict):
            raise TuiPtySpecError(f"steps[{i}].attr must be a mapping")
        # `row:`/`col:` inside `attr:` only *address* the cell — they are
        # skipped by `_do_expect_screen`'s comparison loop, so they are not
        # themselves assertions. Only the remaining keys can ever fail.
        assertable_attr_keys = [
            k for k in (attr or {}) if k not in ("row", "col")
        ]
        if kind == "expect_screen":
            # Checked after the region/attr *shape* checks above so a
            # malformed `region:`/`attr:` still reports that specific
            # problem rather than being masked by these.
            if attr is not None and not assertable_attr_keys:
                # e.g. `attr: {row: 3, col: 5}` — non-empty (so it passes a
                # plain truthiness check) yet addresses a cell without
                # naming anything to compare, leaving the comparison loop
                # with nothing to iterate (#2096).
                raise TuiPtySpecError(
                    f"steps[{i}] (type='expect_screen') has an 'attr:' "
                    f"mapping with no cell attribute to compare — 'row:' "
                    f"and 'col:' only address the cell; add at least one "
                    f"attribute key (e.g. 'bold: true'), otherwise it has "
                    f"nothing to assert and can never fail"
                )
            if not entry.get("text") and not assertable_attr_keys:
                # Neither alternative supplied means the step body
                # (`_do_expect_screen`) has nothing to check against and
                # would silently always pass — a gate that can never fail.
                raise TuiPtySpecError(
                    f"steps[{i}] (type='expect_screen') must supply 'text:' "
                    f"and/or 'attr:' — otherwise it has nothing to assert "
                    f"and can never fail"
                )

        steps.append(SmokeStep(
            kind=kind,
            index=i,
            id=str(entry.get("id", "") or ""),
            key=str(entry.get("key", "") or ""),
            row=_int_default(entry.get("row"), 0),
            col=_int_default(entry.get("col"), 0),
            to_row=_int_default(entry.get("to_row"), 0),
            to_col=_int_default(entry.get("to_col"), 0),
            button=button,
            ms=_int_default(entry.get("ms"), 200),
            timeout_ms=_int_default(entry.get("timeout_ms"), 5000),
            seconds=_float_default(entry.get("seconds"), 1.0),
            text=str(entry.get("text", "") or ""),
            region=region,
            attr=attr,
            cols=_int_default(entry.get("cols"), 0),
            rows=_int_default(entry.get("rows"), 0),
            path=str(entry.get("path", "") or ""),
            contains=str(entry.get("contains", "") or ""),
        ))

    return SmokeSpec(
        name=str(raw.get("name", "") or ""),
        cols=int(raw.get("cols", 80) or 80),
        rows=int(raw.get("rows", 24) or 24),
        steps=tuple(steps),
    )


# ── raw terminal-byte encoding ──────────────────────────────────────────────

_F_KEYS = {
    "f1": b"\x1bOP", "f2": b"\x1bOQ", "f3": b"\x1bOR", "f4": b"\x1bOS",
    "f5": b"\x1b[15~", "f6": b"\x1b[17~", "f7": b"\x1b[18~", "f8": b"\x1b[19~",
    "f9": b"\x1b[20~", "f10": b"\x1b[21~", "f11": b"\x1b[23~", "f12": b"\x1b[24~",
    # F13-F20: the same xterm tilde-encoding convention, continued. F21-F24
    # have no standardized xterm encoding at all — deliberately absent, so
    # :func:`_encode_tui_chord` raises :class:`~coord.key_spec.UnsupportedKey`
    # for them rather than guessing (#3639).
    "f13": b"\x1b[25~", "f14": b"\x1b[26~", "f15": b"\x1b[28~", "f16": b"\x1b[29~",
    "f17": b"\x1b[31~", "f18": b"\x1b[32~", "f19": b"\x1b[33~", "f20": b"\x1b[34~",
}

_NAMED_KEYS = {
    "enter": b"\r",
    "esc": b"\x1b",
    "tab": b"\t",
    "backspace": b"\x7f",
    "space": b" ",
    "up": b"\x1b[A", "down": b"\x1b[B", "right": b"\x1b[C", "left": b"\x1b[D",
    "home": b"\x1b[H", "end": b"\x1b[F",
    "pageup": b"\x1b[5~", "pagedown": b"\x1b[6~",
    "delete": b"\x1b[3~", "insert": b"\x1b[2~",
    **_F_KEYS,
}

#: xterm's modifyOtherKeys modifier parameter for the CSI forms below
#: (``CSI 1 ; <code> <letter>`` for arrows/home/end/F1-F4, ``CSI <num> ;
#: <code> ~`` for pageup/pagedown/delete/insert/F5+) — the same encoding
#: real terminals (and crossterm/ratatui's own decoder, what vimcode is
#: built on) use for every modified non-character key.
_MOD_CODE = {
    frozenset({"shift"}): 2,
    frozenset({"alt"}): 3,
    frozenset({"shift", "alt"}): 4,
    frozenset({"ctrl"}): 5,
    frozenset({"shift", "ctrl"}): 6,
    frozenset({"ctrl", "alt"}): 7,
    frozenset({"shift", "ctrl", "alt"}): 8,
}

_ARROW_FINAL = {"up": "A", "down": "B", "right": "C", "left": "D"}
_HOME_END_FINAL = {"home": "H", "end": "F"}
_TILDE_CODE = {"pageup": "5", "pagedown": "6", "delete": "3", "insert": "2"}
_F_LETTER_FINAL = {"f1": "P", "f2": "Q", "f3": "R", "f4": "S"}
_F_TILDE_NUM = {
    "f5": "15", "f6": "17", "f7": "18", "f8": "19", "f9": "20", "f10": "21",
    "f11": "23", "f12": "24", "f13": "25", "f14": "26", "f15": "28",
    "f16": "29", "f17": "31", "f18": "32", "f19": "33", "f20": "34",
}


#: The canonical modifier order the usage line advertises
#: (``ctrl+alt+shift``) — used to spell an :class:`UnsupportedKey` message
#: the same way, rather than alphabetically (#3639 review nit: alphabetical
#: sort reads ``alt+ctrl+shift``).
_MOD_ORDER: tuple[str, ...] = ("ctrl", "alt", "shift", "cmd")


def _describe_chord(chord: KeyChord) -> str:
    """A human-readable ``mod+mod+base`` spelling of *chord*, for an
    :class:`~coord.key_spec.UnsupportedKey` message."""
    mods = "+".join(m for m in _MOD_ORDER if m in chord.modifiers)
    return f"{mods}+{chord.base}" if mods else chord.base


def _encode_modified_named(chord: KeyChord) -> bytes:
    """The CSI/ESC-prefixed encoding for a NAMED key with at least one
    modifier. Raises :class:`~coord.key_spec.UnsupportedKey` for a
    modifier combination with no terminal encoding at all (``cmd`` — a
    terminal has no Cmd/Super/Meta key, #3639) or an F-key beyond F20."""
    base = chord.base
    if "cmd" in chord.modifiers:
        raise UnsupportedKey(
            "tui-pty", _describe_chord(chord),
            "terminals have no Cmd/Super/Meta key — only Ctrl/Alt/Shift",
        )
    mod_code = _MOD_CODE.get(chord.modifiers)
    if mod_code is not None:
        if base in _ARROW_FINAL:
            return f"\x1b[1;{mod_code}{_ARROW_FINAL[base]}".encode("ascii")
        if base in _HOME_END_FINAL:
            return f"\x1b[1;{mod_code}{_HOME_END_FINAL[base]}".encode("ascii")
        if base in _TILDE_CODE:
            return f"\x1b[{_TILDE_CODE[base]};{mod_code}~".encode("ascii")
        if base in _F_LETTER_FINAL:
            return f"\x1b[1;{mod_code}{_F_LETTER_FINAL[base]}".encode("ascii")
        if base in _F_TILDE_NUM:
            return f"\x1b[{_F_TILDE_NUM[base]};{mod_code}~".encode("ascii")
    if chord.modifiers == frozenset({"alt"}) and base in _NAMED_KEYS:
        # Alt + a named key with no CSI form above (enter/esc/tab/
        # backspace/space): the universal terminal "meta sends ESC"
        # convention — an ESC byte followed by the key's own encoding.
        return b"\x1b" + _NAMED_KEYS[base]
    raise UnsupportedKey(
        "tui-pty", _describe_chord(chord),
        "no terminal encoding for this modifier combination",
    )


def _encode_tui_chord(chord: KeyChord) -> bytes:
    """The raw terminal bytes for one already-parsed
    :class:`~coord.key_spec.KeyChord`. Raises
    :class:`~coord.key_spec.UnsupportedKey` (naming ``"tui-pty"``) for a
    chord no real terminal byte stream can express: ``cmd``/``super``/
    ``meta`` (terminals have no such key — the #3639 acceptance example),
    an F-key beyond F20, or a modifier combination on a plain character
    with no terminal convention — never a silent no-op."""
    if not chord.is_char:
        if not chord.modifiers:
            encoded = _NAMED_KEYS.get(chord.base)
            if encoded is None:
                raise UnsupportedKey(
                    "tui-pty", chord.base, "no terminal encoding for this named key"
                )
            return encoded
        return _encode_modified_named(chord)

    ch = chord.base
    mods = chord.modifiers
    if not mods:
        return ch.encode("utf-8")
    if mods == frozenset({"ctrl"}) and len(ch) == 1 and ch.isalpha():
        # Case-insensitive: Ctrl+c and Ctrl+C are the same physical
        # keystroke and the same control code on every real terminal.
        return bytes([ord(ch.lower()) - ord("a") + 1])
    if mods == frozenset({"alt"}):
        # The universal terminal "meta sends ESC" convention — case
        # preserved, so `alt+M` (Alt+Shift+m) differs from `alt+m`.
        return b"\x1b" + ch.encode("utf-8")
    if mods == frozenset({"shift"}) and len(ch) == 1 and ch.isalpha():
        return ch.upper().encode("utf-8")
    raise UnsupportedKey(
        "tui-pty", _describe_chord(chord),
        "no terminal encoding for this modifier combination on a plain character",
    )


def encode_key(key: str) -> bytes:
    """Encode one ``key:`` token — a single chord, not a chord sequence —
    into the raw bytes a real terminal would send for it. Parsed under the
    grammar shared by all four drivers (:mod:`coord.key_spec`, #3639).

    Raises :class:`TuiPtySpecError` for a *key* that doesn't parse under the
    shared grammar at all (wraps :class:`~coord.key_spec.KeySpecError`) or
    that parses as more than one chord (use :func:`encode_key_sequence` for
    a chord sequence like ``ctrl+k ctrl+w``), and
    :class:`~coord.key_spec.UnsupportedKey` for a chord that parses fine but
    has no terminal byte encoding (``cmd+c`` — see :func:`_encode_tui_chord`).
    """
    try:
        event = parse_key_spec(key)
    except KeySpecError as e:
        raise TuiPtySpecError(f"unrecognized key {key!r}: {e}") from e
    if len(event.chords) != 1:
        raise TuiPtySpecError(
            f"{key!r} is a chord sequence, not one key — call "
            f"encode_key_sequence for that"
        )
    return _encode_tui_chord(event.chords[0])


def encode_key_sequence(key: str) -> list[bytes]:
    """Encode *key* — one chord, or a space-separated chord sequence
    (``ctrl+k ctrl+w``) — into the raw bytes for each chord, in order. What
    :meth:`SmokeRunner._do_key` actually calls, so a single-chord ``key:``
    value still goes through exactly one :func:`_encode_tui_chord` call."""
    try:
        event = parse_key_spec(key)
    except KeySpecError as e:
        raise TuiPtySpecError(f"unrecognized key {key!r}: {e}") from e
    return [_encode_tui_chord(chord) for chord in event.chords]


# SGR extended mouse-reporting protocol (`ESC [ < Cb ; Cx ; Cy M` for
# press/wheel, `... m` for release) — 1-indexed coordinates, hence the +1
# below on this module's 0-indexed `row`/`col`.
_BUTTON_CODES = {"left": 0, "middle": 1, "right": 2, "wheel-up": 64, "wheel-down": 65}
_WHEEL_BUTTONS = ("wheel-up", "wheel-down")


def encode_click(row: int, col: int, button: str = "left") -> bytes:
    """Encode a mouse click at 0-indexed ``(row, col)`` as an SGR mouse
    sequence.

    ``button`` is ``left``/``middle``/``right`` (press then release —
    ``M``/``m``) or ``wheel-up``/``wheel-down`` (a single-shot ``M`` event
    only, matching a real scroll wheel's single notch report). Raises
    :class:`TuiPtySpecError` for an unrecognized *button*.
    """
    if button not in _BUTTON_CODES:
        raise TuiPtySpecError(
            f"unrecognized mouse button {button!r} — expected one of "
            f"{', '.join(_VALID_BUTTONS)}"
        )
    code = _BUTTON_CODES[button]
    x, y = col + 1, row + 1
    press = f"\x1b[<{code};{x};{y}M".encode("ascii")
    if button in _WHEEL_BUTTONS:
        return press
    release = f"\x1b[<{code};{x};{y}m".encode("ascii")
    return press + release


#: SGR mouse-motion events set bit 32 (``0x20``) on the button code —
#: "this button is still held while the pointer moves" — the same bit real
#: terminals set for a press-drag sequence; see ``encode_drag``.
_SGR_MOTION_BIT = 32


def encode_drag(row: int, col: int, to_row: int, to_col: int, button: str = "left") -> bytes:
    """Encode a press-drag-release gesture (#3604) as three SGR mouse
    events: a press at 0-indexed ``(row, col)``, one motion event at
    ``(to_row, to_col)`` with the button-held bit set
    (:data:`_SGR_MOTION_BIT`) — a real terminal reports every intermediate
    cell the pointer crosses, but one motion event at the endpoint is
    enough for an app that reacts to "where did the drag end", which is
    every selection/resize-handle journey this exists for — and a release
    there.

    ``button`` is ``left``/``middle``/``right`` only (:data:`_DRAG_BUTTONS`
    — a wheel notch has no held state to drag with). Raises
    :class:`TuiPtySpecError` for anything else, including a wheel button.
    """
    if button not in _DRAG_BUTTONS:
        raise TuiPtySpecError(
            f"unrecognized drag button {button!r} — expected one of "
            f"{', '.join(_DRAG_BUTTONS)} (a wheel has no held state to "
            f"drag with)"
        )
    code = _BUTTON_CODES[button]
    x0, y0 = col + 1, row + 1
    x1, y1 = to_col + 1, to_row + 1
    press = f"\x1b[<{code};{x0};{y0}M".encode("ascii")
    motion = f"\x1b[<{code + _SGR_MOTION_BIT};{x1};{y1}M".encode("ascii")
    release = f"\x1b[<{code};{x1};{y1}m".encode("ascii")
    return press + motion + release


# ── VT screen ────────────────────────────────────────────────────────────────

def _import_pyte():
    try:
        import pyte  # noqa: PLC0415
    except ModuleNotFoundError as exc:
        raise TuiPtyRuntimeError(
            "tui-pty needs the 'tui-pty' extra, which is not installed "
            "(missing 'pyte').\n"
            "  Install it with:  pip install 'code-coordinator[tui-pty]'"
        ) from exc
    return pyte


def _region_bounds(region: dict | None, total_rows: int, total_cols: int) -> tuple[int, int, int, int]:
    if not region:
        return 0, 0, total_rows, total_cols
    row0 = int(region.get("row", 0))
    col0 = int(region.get("col", 0))
    height = int(region.get("height", max(total_rows - row0, 0)))
    width = int(region.get("width", max(total_cols - col0, 0)))
    return row0, col0, height, width


class VtScreen:
    """A VT100/xterm screen fed the child's raw output byte stream, via
    `pyte` (the ``tui-pty`` extra) — this module never reimplements a
    terminal emulator from scratch, it reads one.
    """

    def __init__(self, cols: int, rows: int) -> None:
        pyte = _import_pyte()
        self._screen = pyte.Screen(cols, rows)
        self._stream = pyte.ByteStream(self._screen)

    def feed(self, data: bytes) -> None:
        self._stream.feed(data)

    def text(self, region: dict | None = None) -> str:
        """The rendered lines within *region* (or the whole screen when
        ``None``), one screen row per output line.

        Built from the raw cell buffer rather than ``pyte``'s own
        ``Screen.display`` property. ``display`` *skips* the stub cell
        that trails a double-width glyph (CJK, emoji, ...) instead of
        padding it, so any row containing even one wide character
        renders exactly one character shorter than ``self.columns`` —
        silently truncating whatever text follows the glyph on that
        row (e.g. a right-flushed status-bar field). We render each
        stub cell back as a single space so every returned row is
        always exactly ``self._screen.columns`` characters wide,
        regardless of what the row contains.
        """
        screen = self._screen
        total_rows = screen.lines
        total_cols = screen.columns
        row0, col0, height, width = _region_bounds(region, total_rows, total_cols)

        def render_row(y: int) -> str:
            row = screen.buffer[y]
            # A stub cell (the trailing half of a double-width glyph)
            # has ``data == ""``; every other cell — including a
            # genuinely blank one — has at least a space.
            return "".join(row[x].data or " " for x in range(total_cols))

        lines = [render_row(y) for y in range(row0, row0 + height)]
        return "\n".join(line[col0:col0 + width] for line in lines)

    def cell_attr(self, row: int, col: int, attr: str):
        """One SGR/text attribute (``bold``, ``italics``, ``underscore``,
        ``strikethrough``, ``reverse``, ``fg``, ``bg``, ...) of the pyte
        ``Char`` at ``(row, col)``."""
        char = self._screen.buffer[row][col]
        return getattr(char, attr)

    def cursor(self) -> tuple[int, int]:
        """The current cursor position as ``(row, col)``, 0-indexed."""
        cursor = self._screen.cursor
        return cursor.y, cursor.x

    def resize(self, rows: int, cols: int) -> None:
        """Resize the VT screen to match a real ``resize`` step (#3604) —
        a thin wrapper over pyte's own ``Screen.resize(lines, columns)``;
        this module keeps its own parameter order (rows first) to match
        every other ``resize``-shaped call in this module."""
        self._screen.resize(rows, cols)


# ── pty/ConPTY child process ────────────────────────────────────────────────

class PtyChild(Protocol):
    """The minimal interface :class:`SmokeRunner` drives a child process
    through — implemented for real by :class:`UnixPtyChild` /
    :class:`WindowsConPtyChild`, and by a scripted fake in this module's
    unit tests (``tests/test_tui_pty_driver.py``)."""

    def write(self, data: bytes) -> None: ...

    def read(self, timeout: float) -> bytes:
        """Return whatever output bytes are available within *timeout*
        seconds, or ``b""`` if none arrived (never blocks past *timeout*)."""
        ...

    def is_alive(self) -> bool: ...

    def close(self) -> None: ...

    def resize(self, cols: int, rows: int) -> None:
        """Live-resize the pty/ConPTY itself to *cols* x *rows* (#3604) —
        the kernel/ConPTY side of a ``resize`` step; the VT screen side is
        :meth:`VtScreen.resize`, called separately by
        :meth:`SmokeRunner._do_resize`."""
        ...


#: Linux's ``prctl(2)`` opcode for ``PR_SET_PDEATHSIG`` — not exposed by the
#: stdlib, so :func:`_arm_parent_death_signal` calls it via ``ctypes``
#: against ``libc.so.6`` rather than pulling in a dependency for one int.
_PR_SET_PDEATHSIG = 1


def _arm_parent_death_signal() -> None:
    """Run in the forked child, before ``exec`` (#3583): arm a
    kernel-enforced "kill me if my parent dies" signal, so the real binary
    this driver launches is reaped even if the Python process managing it
    is killed abnormally (SIGKILL, OOM, crash) — the one case no userspace
    cleanup code (``close()``, ``__del__``, ``atexit``, a signal handler)
    can ever run for, since SIGKILL cannot be caught.

    ``os.setsid()`` detaches the child into its own session/process group
    (needed so it gets its own controlling tty from the pty) — which also
    means it is no longer reachable by a plain ``kill`` of the parent's
    process group, so a death signal is the only remaining guarantee.
    ``PR_SET_PDEATHSIG`` is preserved across ``execve()`` (POSIX.1-2001),
    so it still applies to the real compiled binary this ``shell=True``
    command ultimately execs into — **provided** that exec genuinely
    replaces this process rather than a shell forking a fresh grandchild
    for it (see :data:`coord.shell_exec_wrap.EXEC_PREFIX` on why the launch
    command is wrapped in ``exec`` to force exactly that).

    Linux-only (``prctl`` doesn't exist on macOS/BSD); best-effort — a
    missing/broken ``libc`` symbol must never prevent the pty from
    launching at all, so failures here are swallowed rather than raised.
    """
    if not sys.platform.startswith("linux"):
        return
    try:
        import ctypes  # noqa: PLC0415

        libc = ctypes.CDLL("libc.so.6", use_errno=True)
        # Explicit, rather than relying on ctypes' default-`c_int`
        # argument-promotion guess for an unannotated function pointer —
        # `prctl(2)`'s real signature is `int prctl(int, unsigned long,
        # unsigned long, unsigned long, unsigned long)`.
        libc.prctl.argtypes = [
            ctypes.c_int, ctypes.c_ulong, ctypes.c_ulong, ctypes.c_ulong, ctypes.c_ulong,
        ]
        libc.prctl.restype = ctypes.c_int
        libc.prctl(_PR_SET_PDEATHSIG, signal.SIGKILL, 0, 0, 0)
    except (OSError, AttributeError):
        # OSError: libc.so.6 can't be loaded (unlikely on real Linux glibc).
        # AttributeError: the `prctl` symbol lookup itself fails — ctypes
        # raises this, not OSError, so it must be caught here too for the
        # "never raised, best-effort" guarantee to actually hold.
        pass


def _unix_pty_preexec() -> None:
    """``preexec_fn`` for :class:`UnixPtyChild`'s ``subprocess.Popen`` —
    gives the child its own session (for proper tty signal delivery) and
    arms its parent-death signal (#3583). Order matters: ``setsid()`` does
    not fork and does not clear a death signal armed before or after it,
    but a careless addition of a *fork* between these two calls would."""
    os.setsid()  # NOTE: order vs the next line doesn't matter today (see
    # docstring) — but a fork inserted between them would break that.
    _arm_parent_death_signal()  # NOTE: see the NOTE above this call.


class UnixPtyChild:
    """A real Unix pty running *command* under a real child process (#3483)
    — not an in-process harness. Requires a POSIX platform (:mod:`pty` is
    POSIX-only in the standard library).

    #3583: the spawned child also has a kernel-enforced parent-death signal
    armed (:func:`_arm_parent_death_signal`, Linux-only) so it is reaped
    even if this driver's own Python process is killed abnormally before
    :meth:`close` ever runs — see that function's docstring. This is a
    defense in depth with, not a replacement for, :meth:`close`: a normal
    teardown still explicitly terminates/kills the child.
    """

    def __init__(self, command: str, cwd: str, cols: int, rows: int) -> None:
        if os.name != "posix":
            raise TuiPtyRuntimeError(
                "UnixPtyChild requires a POSIX platform — use "
                "WindowsConPtyChild on Windows"
            )
        import fcntl  # noqa: PLC0415
        import pty  # noqa: PLC0415
        import struct  # noqa: PLC0415
        import termios  # noqa: PLC0415

        master_fd, slave_fd = pty.openpty()
        fcntl.ioctl(slave_fd, termios.TIOCSWINSZ, struct.pack("HHHH", rows, cols, 0, 0))
        try:
            self._proc = subprocess.Popen(
                _wrap_launch_command(command), shell=True, cwd=cwd or None,
                stdin=slave_fd, stdout=slave_fd, stderr=slave_fd,
                preexec_fn=_unix_pty_preexec, close_fds=True,
            )
        finally:
            os.close(slave_fd)
        self._master_fd = master_fd
        os.set_blocking(self._master_fd, False)
        self._closed = False

    def write(self, data: bytes) -> None:
        os.write(self._master_fd, data)

    def read(self, timeout: float) -> bytes:
        import select  # noqa: PLC0415

        ready, _, _ = select.select([self._master_fd], [], [], timeout)
        if not ready:
            return b""
        try:
            return os.read(self._master_fd, 65536)
        except OSError:
            return b""

    @property
    def pid(self) -> int:
        """The real pty child's pid (#3590) — for the common
        single-simple-command launch, :func:`_wrap_launch_command`'s
        ``exec`` means this ``Popen`` pid IS the real binary's own pid
        (the shell process image was replaced, not forked), so this is
        safe to re-observe/re-signal directly as the driven app's pid.
        :class:`coord.mac_native_driver.MacOSCalls.launch` shares the exact
        same :func:`coord.shell_exec_wrap.wrap_launch_command` for the same
        reason (#3622) — see :class:`coord.mac_native_driver
        .MacNativeSession.pid`."""
        return self._proc.pid

    def is_alive(self) -> bool:
        return self._proc.poll() is None

    def resize(self, cols: int, rows: int) -> None:
        """Live-resize this pty (#3604) via the same ``TIOCSWINSZ`` ioctl
        used at launch — issuing it against the (still-open) master fd
        changes the slave's reported window size and the kernel delivers
        ``SIGWINCH`` to the slave's foreground process group automatically;
        no separate signal call is needed, unlike a real terminal emulator
        which issues both itself for the same reason."""
        import fcntl  # noqa: PLC0415
        import struct  # noqa: PLC0415
        import termios  # noqa: PLC0415

        fcntl.ioctl(self._master_fd, termios.TIOCSWINSZ, struct.pack("HHHH", rows, cols, 0, 0))

    def close(self) -> None:
        if self._closed:
            return
        self._closed = True
        if self._proc.poll() is None:
            self._proc.terminate()
            try:
                self._proc.wait(timeout=3)
            except subprocess.TimeoutExpired:
                self._proc.kill()
                # #3590 review: re-observe after the kill too — the
                # previous version sent SIGKILL and declared victory
                # without ever confirming it landed, overstating what
                # "confirmed terminate-then-kill" (this class's own
                # module/TuiPtySession docstrings) actually means. SIGKILL
                # cannot be blocked, so this wait is bounded and
                # best-effort only against a process already wedged in
                # uninterruptible kernel sleep.
                try:
                    self._proc.wait(timeout=3)
                except subprocess.TimeoutExpired:
                    pass
        try:
            os.close(self._master_fd)
        except OSError:
            pass


class WindowsConPtyChild:
    """A real Windows ConPTY session running *command* (#3483), via the
    optional ``pywinpty`` package (the ``tui-pty`` extra's Windows-only
    dependency).

    A background reader thread continuously drains ``pywinpty``'s own
    (blocking) ``read()`` into a queue, so :meth:`read` can honor the same
    "never block past *timeout*" contract :class:`UnixPtyChild` does without
    spawning a new thread per call.
    """

    def __init__(self, command: str, cwd: str, cols: int, rows: int) -> None:
        try:
            from winpty import PtyProcess  # noqa: PLC0415
        except ModuleNotFoundError as exc:
            raise TuiPtyRuntimeError(
                "tui-pty on Windows needs the 'tui-pty' extra, which is not "
                "installed (missing 'pywinpty').\n"
                "  Install it with:  pip install 'code-coordinator[tui-pty]'"
            ) from exc

        self._proc = PtyProcess.spawn(command, cwd=cwd or None, dimensions=(rows, cols))
        self._chunks: "queue.Queue[bytes]" = queue.Queue()
        self._reader_thread = threading.Thread(target=self._read_loop, daemon=True)
        self._reader_thread.start()

    def _read_loop(self) -> None:
        while True:
            try:
                chunk = self._proc.read(65536)
            except Exception:  # noqa: BLE001 — pywinpty raises on EOF/close
                return
            if not chunk:
                return
            data = chunk.encode("utf-8", errors="replace") if isinstance(chunk, str) else chunk
            self._chunks.put(data)

    def write(self, data: bytes) -> None:
        self._proc.write(data.decode("utf-8", errors="replace"))

    def read(self, timeout: float) -> bytes:
        try:
            return self._chunks.get(timeout=timeout)
        except queue.Empty:
            return b""

    @property
    def pid(self) -> int | None:
        """``pywinpty``'s own child pid (#3590), when it exposes one —
        best-effort, since this is read via ``getattr`` by callers rather
        than assumed present on every ``pywinpty`` version."""
        return getattr(self._proc, "pid", None)

    def is_alive(self) -> bool:
        return bool(self._proc.isalive())

    def resize(self, cols: int, rows: int) -> None:
        """Live-resize this ConPTY session (#3604) via ``pywinpty``'s own
        ``setwinsize`` — the Windows analogue of :meth:`UnixPtyChild.resize`'s
        ``TIOCSWINSZ`` ioctl; ``pywinpty`` takes the same ``(rows, cols)``
        order :meth:`__init__` already passes it as ``dimensions``."""
        self._proc.setwinsize(rows, cols)

    def close(self) -> None:
        try:
            self._proc.close(force=True)
        except Exception:  # noqa: BLE001
            pass


# ── smoke-spec runner ───────────────────────────────────────────────────────

_CPR_QUERY = b"\x1b[6n"
_READ_POLL_S = 0.05


class _CprResponder:
    """Answers a VT100 cursor-position-report query (``ESC[6n``) with the
    current cursor position — the ONE implementation both
    :class:`SmokeRunner` and :class:`TuiPtySession` share (#3603, #2096
    "one question, one answer").

    Before this, :class:`TuiPtySession` had no CPR-reply logic at all,
    while :class:`SmokeRunner` did — two independent implementations of
    "does this reader loop answer a terminal query" that had already
    drifted. The practical effect (#3603): ``coord app-drive tui-pty open``
    launched ``vcd`` under a real pty exactly like ``run-spec`` does, but
    never answered its startup ``ESC[6n`` query, so the app gave up and
    exited within a few seconds with the screen still blank — while the
    identical launch command through ``run-spec`` (:class:`SmokeRunner`,
    which DID answer it) ran a 490-step spec with no instability.

    Reading and replying are split across two threads for the reason this
    module's own docstring documents: on a real Windows ConPTY, answering
    synchronously from inside the byte-stream reader callback deadlocks the
    session. :meth:`observe` is called from the reader thread, AFTER the
    caller has already fed *data* to its :class:`VtScreen` (so
    :meth:`VtScreen.cursor` reflects it); the reply is only ever WRITTEN
    from this class's own responder thread.
    """

    def __init__(self, child: PtyChild) -> None:
        self._child = child
        self._queue: "queue.Queue[bytes]" = queue.Queue()
        self._stop = threading.Event()
        self._thread = threading.Thread(target=self._loop, daemon=True)
        self._thread.start()

    def observe(self, data: bytes, screen: VtScreen) -> None:
        """If *data* contains a CPR query, enqueue the reply the responder
        thread will write. A no-op when it doesn't."""
        if _CPR_QUERY in data:
            row, col = screen.cursor()
            self._queue.put(f"\x1b[{row + 1};{col + 1}R".encode("ascii"))

    def _loop(self) -> None:
        while not self._stop.is_set():
            try:
                reply = self._queue.get(timeout=0.1)
            except queue.Empty:
                continue
            try:
                self._child.write(reply)
            except Exception:  # noqa: BLE001 — child may have exited underneath us
                return

    def close(self) -> None:
        self._stop.set()
        self._thread.join(timeout=2)


class SmokeRunner:
    """Drives one :class:`SmokeSpec` against a real :class:`PtyChild`,
    producing coord's normalized ``{"id", "status", "message"}`` verdict
    list — the same shape :func:`coord.acceptance_drivers.parse_test_output`
    already produces for ``tui-tuidriver``.

    ``spawn_child`` is injected (not hardcoded to Unix/Windows) so unit
    tests can drive this against a scripted :class:`PtyChild` fake without
    a real terminal — see ``tests/test_tui_pty_driver.py``.
    """

    def __init__(
        self, spawn_child: Callable[[int, int], PtyChild], *, deadline: float | None = None,
    ) -> None:
        self._spawn_child = spawn_child
        self._deadline = deadline  # a `time.monotonic()` value, or None for no overall cap
        self._child: PtyChild | None = None
        self._screen: VtScreen | None = None
        self._cols = 0
        self._rows = 0
        self._lock = threading.Lock()
        self._total_bytes = 0
        self._last_byte_time = 0.0
        self._stop = threading.Event()
        self._cpr_responder: _CprResponder | None = None
        self._reader_thread: threading.Thread | None = None

    def run(self, spec: SmokeSpec) -> list[dict]:
        self._cols, self._rows = spec.cols, spec.rows
        results: list[dict] = []
        try:
            for step in spec.steps:
                if self._deadline is not None and time.monotonic() >= self._deadline:
                    # The driver-level `timeout:` was exhausted by earlier
                    # steps (each of which has its own bounded per-step
                    # budget, but their sum can still exceed it) — fail the
                    # remaining steps explicitly rather than silently
                    # truncating the report, or worse, blocking past it.
                    results.append({
                        "id": step.step_id, "status": "fail",
                        "message": "aborted: tui-pty driver-level timeout exceeded",
                    })
                    continue
                results.append(self._run_step(step))
        finally:
            self._teardown()
        return results

    def _run_step(self, step: SmokeStep) -> dict:
        handlers = {
            "launch": self._do_launch,
            "key": self._do_key,
            "click": self._do_click,
            "drag": self._do_drag,
            "resize": self._do_resize,
            "wait_idle": self._do_wait_idle,
            "expect_screen": self._do_expect_screen,
            "expect_silent": self._do_expect_silent,
            "expect_within": self._do_expect_within,
            "type_text": self._do_type_text,
            "expect_file": self._do_expect_file,
        }
        try:
            handlers[step.kind](step)
        except (TuiPtySpecError, TuiPtyRuntimeError, UnsupportedKey, AssertionError) as e:
            return {"id": step.step_id, "status": "fail", "message": str(e)}
        return {"id": step.step_id, "status": "pass", "message": ""}

    # -- action steps --

    def _do_launch(self, step: SmokeStep) -> None:
        self._child = self._spawn_child(self._cols, self._rows)
        self._screen = VtScreen(self._cols, self._rows)
        self._stop.clear()
        with self._lock:
            # Idle timing is measured from "since the last byte arrived (or
            # since launch, if none has yet)" — not from the process epoch,
            # which would otherwise read as "already idle" the instant any
            # step runs, regardless of whether the app has settled.
            self._last_byte_time = time.monotonic()
        self._cpr_responder = _CprResponder(self._child)
        self._reader_thread = threading.Thread(target=self._reader_loop, daemon=True)
        self._reader_thread.start()
        # A brief startup grace window — a binary that fails to exec at all
        # (bad path, missing binary) dies near-instantly; catch that here
        # with an actionable message rather than letting every later step
        # fail against a dead child with no context.
        time.sleep(0.2)
        if not self._child.is_alive():
            raise TuiPtyRuntimeError(
                "child process exited immediately after launch (command "
                "failed to start?)"
            )

    def _require_child(self) -> PtyChild:
        if self._child is None:
            raise TuiPtyRuntimeError("no child process — spec has no 'launch' step before this one")
        return self._child

    def _do_key(self, step: SmokeStep) -> None:
        """#3639: *step.key* may be a space-separated chord sequence
        (``ctrl+k ctrl+w``) — each chord is written as its own byte
        sequence, in order."""
        child = self._require_child()
        for chord_bytes in encode_key_sequence(step.key):
            child.write(chord_bytes)

    def _do_click(self, step: SmokeStep) -> None:
        self._require_child().write(encode_click(step.row, step.col, step.button))

    def _do_type_text(self, step: SmokeStep) -> None:
        """#3650: the literal bytes of *step.text*, written straight to the
        pty child's stdin — the same :meth:`PtyChild.write` every other
        action step already goes through, i.e. real OS input, never an
        in-process injection into the app's own buffer."""
        self._require_child().write(step.text.encode("utf-8"))

    def _do_drag(self, step: SmokeStep) -> None:
        self._require_child().write(
            encode_drag(step.row, step.col, step.to_row, step.to_col, step.button)
        )

    def _do_resize(self, step: SmokeStep) -> None:
        """Live-resize both halves #3604 needs kept in sync: the real
        pty/ConPTY (so the driven app's own ``SIGWINCH``/resize-event
        handling actually fires) and this runner's :class:`VtScreen` (so
        the NEXT ``expect_screen``/``expect_within`` step reads the new
        dimensions rather than the stale launch-time ones) — done under
        the same lock :meth:`_do_expect_screen` takes, so neither can
        observe the screen mid-resize."""
        child = self._require_child()
        child.resize(step.cols, step.rows)
        with self._lock:
            assert self._screen is not None
            self._screen.resize(step.rows, step.cols)
        self._cols, self._rows = step.cols, step.rows

    def _do_wait_idle(self, step: SmokeStep) -> None:
        idle_for = step.ms / 1000
        deadline = time.monotonic() + step.timeout_ms / 1000
        while True:
            with self._lock:
                since = time.monotonic() - self._last_byte_time
            if since >= idle_for:
                return
            if time.monotonic() >= deadline:
                raise TuiPtyRuntimeError(
                    f"stream never went idle for {step.ms}ms within "
                    f"{step.timeout_ms}ms"
                )
            time.sleep(min(0.02, idle_for))

    # -- assertion steps --

    def _do_expect_screen(self, step: SmokeStep) -> None:
        assert self._screen is not None
        # Guarded by the same lock protecting `_total_bytes`/
        # `_last_byte_time`: `_reader_loop` mutates `self._screen` from a
        # background thread via `feed()`, so an unguarded read here could
        # race a `feed()` still applying an escape sequence.
        with self._lock:
            screen_text = self._screen.text(step.region)
            attr_failure = None
            if step.attr:
                row = int(step.attr.get("row", 0))
                col = int(step.attr.get("col", 0))
                for key, expected in step.attr.items():
                    if key in ("row", "col"):
                        continue
                    actual = self._screen.cell_attr(row, col, key)
                    if actual != expected:
                        attr_failure = (row, col, key, expected, actual)
                        break
        if step.text and step.text not in screen_text:
            region_note = f" in region {step.region}" if step.region else ""
            raise AssertionError(
                f"expected screen text {step.text!r} not found{region_note}; "
                f"screen was:\n{screen_text}"
            )
        if attr_failure is not None:
            row, col, key, expected, actual = attr_failure
            raise AssertionError(
                f"expected cell ({row},{col}).{key} == {expected!r}, "
                f"got {actual!r}"
            )

    def _do_expect_silent(self, step: SmokeStep) -> None:
        """#2096: this can only be answered by actually observing the
        window elapse and re-reading the byte counter afterward — the mere
        absence of an exception during the sleep proves nothing (nothing
        here *can* raise mid-sleep). vimcode#1634's regression: a real ~1
        Hz flicker delivers bytes at roughly 1-second intervals, so a
        window of even a couple of seconds reliably observes at least one."""
        with self._lock:
            before = self._total_bytes
        time.sleep(step.seconds)
        with self._lock:
            after = self._total_bytes
        if after != before:
            raise AssertionError(
                f"expected silence for {step.seconds}s but received "
                f"{after - before} byte(s) of output during the window"
            )

    def _do_expect_within(self, step: SmokeStep) -> None:
        assert self._screen is not None
        deadline = time.monotonic() + step.ms / 1000
        while True:
            with self._lock:
                screen_text = self._screen.text(step.region)
            if step.text in screen_text:
                return
            if time.monotonic() >= deadline:
                raise AssertionError(
                    f"expected {step.text!r} to appear within {step.ms}ms; "
                    f"screen was:\n{screen_text}"
                )
            time.sleep(0.02)

    def _do_expect_file(self, step: SmokeStep) -> None:
        """#3650: delegates to :func:`coord.native_fs_wait.wait_for_file` —
        the one shared filesystem check every Tier-2 native driver's own
        ``expect_file`` step calls through (#2096 "one question, one
        answer"); this driver has no OS-specific behaviour to add on top of
        it."""
        ok, reason = wait_for_file(
            step.path, step.timeout_ms, step.contains or None,
        )
        if not ok:
            raise AssertionError(reason)

    # -- background threads --

    def _reader_loop(self) -> None:
        child = self._child
        screen = self._screen
        assert child is not None and screen is not None
        while not self._stop.is_set():
            data = child.read(_READ_POLL_S)
            if not data:
                if not child.is_alive():
                    return
                continue
            with self._lock:
                self._total_bytes += len(data)
                self._last_byte_time = time.monotonic()
                # `feed()` mutates the screen and `cursor()` reads it back —
                # both under the same lock the assertion steps take before
                # their own `text()`/`cell_attr()` reads, so neither can
                # observe a `VtScreen` mid-mutation.
                screen.feed(data)
                # Reply (if any) is enqueued here, WRITTEN from
                # `_CprResponder`'s own thread — never write the child's
                # stdin synchronously from this thread. See this module's
                # docstring: doing so deadlocks a real Windows ConPTY
                # session.
                assert self._cpr_responder is not None
                self._cpr_responder.observe(data, screen)

    def _teardown(self) -> None:
        self._stop.set()
        if self._reader_thread is not None:
            self._reader_thread.join(timeout=2)
        if self._cpr_responder is not None:
            self._cpr_responder.close()
        if self._child is not None:
            self._child.close()


def spawn_real_pty(command: str, cwd: str, cols: int, rows: int) -> PtyChild:
    """The default ``spawn_child`` for :func:`run_smoke_spec`: a real
    :class:`UnixPtyChild` on POSIX, a real :class:`WindowsConPtyChild` on
    Windows."""
    if os.name == "nt":
        return WindowsConPtyChild(command, cwd, cols, rows)
    return UnixPtyChild(command, cwd, cols, rows)


class TuiPtySession:
    """A persistent, interactively-driven tui-pty session (#3590) — the
    backend ``coord app-drive tui-pty`` (:mod:`coord.app_drive_daemon`)
    holds open across ``send``/``screen``/``wait-idle``/``close`` calls
    that each arrive as a SEPARATE, short-lived ``coord app-drive`` CLI
    invocation (a worker's Bash tool cannot keep one process's stdin open
    across tool calls), rather than :class:`SmokeRunner`'s own "walk one
    fixed step list end to end in a single call" shape.

    Mirrors :class:`SmokeRunner`'s reader-loop/lock discipline and reuses
    the exact same primitives (:func:`encode_key`/:func:`encode_click`/
    :class:`VtScreen`/:func:`spawn_real_pty`) it's built from — this is NOT
    a second, home-made input-injection path (#3566's HARD RULE): it is
    the sanctioned driver, just finally invokable one verb at a time
    instead of only as a whole pre-scripted spec.

    Teardown (:meth:`close`) delegates straight to the child's own
    :meth:`PtyChild.close` — for a real :class:`UnixPtyChild` that is the
    SAME confirmed terminate-then-kill-with-a-timeout teardown every other
    tui-pty caller gets, backed by the kernel-enforced parent-death signal
    armed at launch time (#3583, Linux-only): even an abnormal death of
    whatever process is holding this session (this one, or
    ``coord.app_drive``'s own daemon wrapping it) still reaps the real
    child.

    Also answers the ``ESC[6n`` cursor-position query via the same
    :class:`_CprResponder` :class:`SmokeRunner` uses (#3603): without this,
    a startup-blocking app (ratatui's ``Terminal::new()``, among others —
    see #3603's own evidence) never gets a reply when driven through
    ``coord app-drive tui-pty open`` and gives up within a few seconds,
    even though the identical launch command ran fine through
    :func:`run_smoke_spec`/``run-spec`` — the only thing that differed was
    which of the two reader loops answered this query, so this class now
    shares the ONE answer instead of having none of its own (#2096).
    """

    def __init__(
        self, launch_command: str, cwd: str, cols: int = 80, rows: int = 24,
        spawn_child: Callable[[str, str, int, int], PtyChild] | None = None,
    ) -> None:
        self._cols, self._rows = cols, rows
        self._child: PtyChild = (spawn_child or spawn_real_pty)(launch_command, cwd, cols, rows)
        self._screen = VtScreen(cols, rows)
        self._lock = threading.Lock()
        self._last_byte_time = time.monotonic()
        self._stop = threading.Event()
        self._cpr_responder = _CprResponder(self._child)
        self._reader_thread = threading.Thread(target=self._reader_loop, daemon=True)
        self._reader_thread.start()
        # Same startup-failure confirmation `SmokeRunner._do_launch` makes
        # (#2096: an "opened" verdict must be an observation, not the mere
        # absence of an exception from `Popen`) — a bad launch command
        # dies near-instantly, so catch that here with an actionable
        # message rather than every later verb failing against a dead
        # child with no context.
        time.sleep(0.2)
        if not self._child.is_alive():
            self.close()
            raise TuiPtyRuntimeError(
                "child process exited immediately after launch (command failed to start?)"
            )

    def _reader_loop(self) -> None:
        while not self._stop.is_set():
            try:
                data = self._child.read(_READ_POLL_S)
            except Exception:  # noqa: BLE001 — child may have exited underneath us
                return
            if not data:
                if not self._child.is_alive():
                    return
                continue
            with self._lock:
                self._last_byte_time = time.monotonic()
                self._screen.feed(data)
                # See `_CprResponder`'s own docstring and this class's:
                # the reply (if any) is enqueued here but WRITTEN from the
                # responder's own thread, never synchronously from this one.
                self._cpr_responder.observe(data, self._screen)

    @property
    def pid(self) -> int | None:
        """The real pty child's pid (#3590), when the underlying
        :class:`PtyChild` exposes one (both :class:`UnixPtyChild` and
        :class:`WindowsConPtyChild` do) — read by
        :mod:`coord.app_drive_daemon` for its ready-file's ``app_pid`` so
        :func:`coord.app_drive.close_session` can re-observe/re-signal the
        driven app itself, not just the daemon wrapping this session."""
        return getattr(self._child, "pid", None)

    def send_key(self, key: str) -> None:
        """#3639: *key* may be a space-separated chord sequence
        (``ctrl+k ctrl+w``) — see :meth:`SmokeRunner._do_key`'s own
        docstring for the same contract against a YAML spec step."""
        for chord_bytes in encode_key_sequence(key):
            self._child.write(chord_bytes)

    def send_text(self, text: str) -> None:
        self._child.write(text.encode("utf-8"))

    def send_click(self, row: int, col: int, button: str = "left") -> None:
        self._child.write(encode_click(row, col, button))

    def send_drag(self, row: int, col: int, to_row: int, to_col: int, button: str = "left") -> None:
        """#3604: same primitive :meth:`SmokeRunner._do_drag` uses
        (:func:`encode_drag`) — kept here too so this interactively-driven
        session doesn't drift from the smoke-spec runner (#2096 "one
        question, one answer")."""
        self._child.write(encode_drag(row, col, to_row, to_col, button))

    def resize(self, cols: int, rows: int) -> None:
        """#3604: same two-sided resize :meth:`SmokeRunner._do_resize`
        does — the real pty/ConPTY AND this session's own :class:`VtScreen`,
        under the same lock :meth:`screen_text` takes."""
        self._child.resize(cols, rows)
        with self._lock:
            self._screen.resize(rows, cols)
        self._cols, self._rows = cols, rows

    def wait_idle(self, ms: int = 500, timeout_ms: int = 5000) -> bool:
        """Block until the stream has gone quiet for *ms* milliseconds, or
        *timeout_ms* elapses — returns whether it actually settled (#2096:
        an observed verdict, never assumed from a fixed sleep). Never
        raises."""
        idle_for = ms / 1000
        deadline = time.monotonic() + timeout_ms / 1000
        while True:
            with self._lock:
                since = time.monotonic() - self._last_byte_time
            if since >= idle_for:
                return True
            if time.monotonic() >= deadline:
                return False
            time.sleep(min(0.02, idle_for) if idle_for > 0 else 0.02)

    def screen_text(self, region: dict | None = None) -> str:
        with self._lock:
            return self._screen.text(region)

    def is_alive(self) -> bool:
        return self._child.is_alive()

    def close(self) -> None:
        self._stop.set()
        self._reader_thread.join(timeout=2)
        self._cpr_responder.close()
        self._child.close()


def run_smoke_spec(
    spec_text: str, *, launch_command: str, cwd: str,
    spawn_child: Callable[[int, int], PtyChild] | None = None,
    timeout: float | None = None,
) -> list[dict]:
    """Parse *spec_text* and run it against a real pty/ConPTY launching
    *launch_command* in *cwd* — the top-level entry point
    :func:`coord.acceptance_drivers._run_tui_pty` calls.

    *spawn_child*, when given, overrides how the child process is spawned
    (used by tests to inject a scripted fake — see
    ``tests/test_tui_pty_driver.py``); defaults to :func:`spawn_real_pty`.

    *timeout*, when given, is an overall wall-clock budget in seconds for
    the whole spec (mirrors every other driver kind's own ``timeout:``).
    Each step already carries its own bounded budget (``ms``/``seconds``/
    ``timeout_ms``), but their sum can still exceed *timeout*; once it's
    exhausted, :meth:`SmokeRunner.run` fails every remaining step
    explicitly rather than truncating the report or blocking past it.

    Raises :class:`TuiPtySpecError` for a malformed spec. Runtime failures
    (the child dies, a step times out, an assertion fails) do NOT raise —
    they're folded into the returned list as a ``status="fail"`` entry, the
    same "partial results, not a crash" contract
    :func:`coord.acceptance_drivers.parse_test_output` already gives
    ``tui-tuidriver``.
    """
    spec = parse_smoke_spec(spec_text)

    def _spawn(cols: int, rows: int) -> PtyChild:
        if spawn_child is not None:
            return spawn_child(cols, rows)
        return spawn_real_pty(launch_command, cwd, cols, rows)

    deadline = time.monotonic() + timeout if timeout is not None else None
    runner = SmokeRunner(_spawn, deadline=deadline)
    return runner.run(spec)
