"""``tui-pty`` acceptance driver — Tier 2, real terminal (#3483).

Every black-box driver ``coord`` runs before this one drives the app
**in-process** (``tui-tuidriver`` goes through quadraui's ``TuiDriver``, a
Rust in-memory harness — see CLAUDE.md's coord-tui section). On 2026-09-29,
three real Windows TUI bugs all passed their in-process tests: a ~1 Hz
foreground flicker (vimcode#1634), activity-bar clicks doing nothing
(vimcode#1636), and slow right-click menus (vimcode#1635). The bytes an
in-process harness feeds the app are never generated by a real terminal, and
the bytes it reads back never pass through one either — so a whole class of
bug (idle repaint churn, real input translation, real paint latency) is
invisible to it by construction.

This module is that missing tier: it launches the repo's **real compiled
binary** under a **real pseudo-terminal** — a Unix ``pty`` via the stdlib
:mod:`pty` module on Linux/macOS (:class:`UnixPtyChild`), **ConPTY** on
Windows via the optional ``pywinpty`` package, the ``tui-pty`` extra's
Windows-only dependency (:class:`WindowsConPtyChild`) — sends real terminal
byte sequences (keys, SGR mouse including right-button and wheel), records
the raw output byte stream with timestamps, and feeds it through a VT
emulator (`pyte`, the ``tui-pty`` extra's cross-platform dependency) so
assertions can read the resulting screen grid (cell text and SGR
attributes).

**Smoke spec.** :func:`parse_smoke_spec` reads a platform-neutral YAML file,
checked into the *driven* repo (one file per app — the ``tui-pty`` analogue
of ``tui-tuidriver``'s ``tui/tests/acceptance.rs`` entrypoint; see
:func:`coord.acceptance_drivers._run_tui_pty`'s docstring for how its path
is threaded through as the driver's ``entrypoint:``). Steps:

- ``launch`` — spawn the real binary under the pty/ConPTY.
- ``key: <name>`` — send one key (named: ``enter``, ``esc``, ``tab``,
  ``backspace``, ``space``, arrow keys, ``home``/``end``, ``pageup``/
  ``pagedown``, ``delete``, ``insert``, ``f1``-``f12``, ``ctrl+<letter>``; or
  any single literal character).
- ``click: {row, col, button}`` — an SGR mouse click at 0-indexed
  ``(row, col)``; ``button`` is ``left`` (default), ``middle``, ``right``, or
  ``wheel-up``/``wheel-down`` (single-shot, no release event — mirrors a
  real wheel).
- ``wait_idle: {ms, timeout_ms}`` — block until the byte stream has been
  quiet for ``ms`` milliseconds, or fail after ``timeout_ms`` without ever
  reaching that quiet window (default 5000ms) — a precondition step, not an
  assertion on its own, but still fails the run if the app never settles.
- ``expect_screen: {region, text, attr}`` — the current VT screen (or a
  ``region: {row, col, width, height}`` sub-rectangle) must contain ``text``
  (a plain substring check against the rendered lines) and/or match
  ``attr: {row, col, <pyte Char field>: <expected value>}`` for one cell
  (e.g. ``{row: 3, col: 5, bold: true}``). At least one of ``text``/``attr``
  is required — a step with neither has nothing to assert against and
  could never fail, which :func:`parse_smoke_spec` rejects (#2096).
- ``expect_silent: {seconds}`` — the byte stream must receive **zero**
  bytes over a full ``seconds``-long real-time window. This is vimcode#1634's
  regression check: an idle app that's actually idle produces no repaint
  traffic; a ~1 Hz flicker does. See :meth:`SmokeRunner._do_expect_silent`
  for why this can only be answered by actually waiting out the window and
  re-reading a byte counter afterward, never by the mere absence of an
  exception (#2096: unconfirmed success is a defect).
- ``expect_within: {ms, text, region}`` — ``text`` must appear on the (VT)
  screen within ``ms`` milliseconds of this step starting; polls the live
  screen repeatedly rather than sampling once, so a slow-but-eventual paint
  still passes and a truly-never-appears one genuinely fails at the
  deadline (vimcode#1635's right-click-menu-latency regression check).

**The ``ESC[6n`` cursor-position query lesson (vimcode's own ConPTY tests,
folded in before this issue was dispatched).** ratatui's ``Terminal::new()``
blocks at startup on a Device Status Report reply to the ``ESC[6n`` it
sends — a real terminal answers this "where's the cursor" query
transparently; a driver standing in for one must too, or the app never
paints anything and every subsequent step times out waiting on a blank
screen. **On real Windows ConPTY, answering synchronously from inside the
byte-stream reader callback deadlocks the session** (verified by vimcode's
own ``tests/conpty_idle_flicker.rs``/``tests/conpty_activity_bar_click.rs`,
built with ``portable_pty`` + a ``vt100`` parser for exactly this tier).
:class:`SmokeRunner` therefore splits reading and replying across two
threads: ``_reader_loop`` only reads bytes, feeds the VT screen, and — on
spotting ``ESC[6n`` — enqueues a reply; a separate ``_responder_loop``
dequeues and writes it. Never write the child's stdin from the reader
thread itself.

**What this tier does NOT see** (spelled out in the issue, and important —
see vimcode#3484 for the tier this hands off to): raw ConPTY was not the
last mile for any of the three Windows bugs above. All three *passed* under
a raw ConPTY too — the idle byte stream is genuinely silent (#1634), a
right-click paints in about 50µs measured this way (#1635), activity-bar
clicks work (#1636) — yet the operator still saw flicker, lag and dead
clicks in a real terminal *window*. This driver proves the app's own
behaviour is correct against a real pty; it cannot see a terminal
emulator's own rendering/input-translation behaviour (Windows Terminal,
legacy conhost, iTerm, GNOME Terminal) — that needs a native kind driving
and capturing an actual terminal window (vimcode#3484).
"""

from __future__ import annotations

import os
import queue
import re
import subprocess
import threading
import time
from dataclasses import dataclass
from typing import Callable, Protocol

import yaml


class TuiPtySpecError(Exception):
    """Raised for a malformed smoke spec: invalid YAML, a missing/empty
    ``steps:`` list, an unknown step ``type``, a missing required field, or
    an unrecognized key/button name."""


class TuiPtyRuntimeError(Exception):
    """Raised when the pty/ConPTY child itself can't be spawned or driven:
    missing platform support, a missing optional dependency (the
    ``tui-pty`` extra), the child process dying unexpectedly, or a
    ``wait_idle`` step that never sees the stream go quiet."""


# ── smoke spec model ────────────────────────────────────────────────────────

_REQUIRED_FIELDS: dict[str, tuple[str, ...]] = {
    "launch": (),
    "key": ("key",),
    "click": ("row", "col"),
    "wait_idle": (),
    "expect_screen": (),
    "expect_silent": (),
    "expect_within": ("text",),
}

_VALID_BUTTONS = ("left", "middle", "right", "wheel-up", "wheel-down")


@dataclass(frozen=True)
class SmokeStep:
    """One parsed step of a smoke spec.

    ``kind`` selects the step type; every field this step type doesn't use
    keeps its default so callers never have to branch on ``kind`` before
    reading one.
    """

    kind: str
    index: int
    id: str = ""
    key: str = ""
    row: int = 0
    col: int = 0
    button: str = "left"
    ms: int = 200
    timeout_ms: int = 5000
    seconds: float = 1.0
    text: str = ""
    region: dict | None = None
    attr: dict | None = None

    @property
    def step_id(self) -> str:
        """The normalized ``tests[].id`` this step reports under — the
        spec author's own ``id:`` when given (so a named regression, e.g.
        vimcode#1634's ``idle-flicker-1634``, stays a stable id across
        unrelated spec edits), else a positional fallback."""
        return self.id or f"{self.index:03d} {self.kind}"


@dataclass(frozen=True)
class SmokeSpec:
    name: str
    cols: int
    rows: int
    steps: tuple[SmokeStep, ...]


def _int_default(value, default: int) -> int:
    """``int(value)``, falling back to *default* only when *value* is
    absent (``None``) — unlike the ``int(value or default)`` idiom, an
    explicit literal ``0`` in the YAML is honored rather than silently
    treated as "absent"."""
    return default if value is None else int(value)


def _float_default(value, default: float) -> float:
    """The :func:`_int_default` idiom for a ``float`` field."""
    return default if value is None else float(value)


def parse_smoke_spec(yaml_text: str) -> SmokeSpec:
    """Parse a platform-neutral smoke-spec YAML document into a
    :class:`SmokeSpec`.

    Top level: ``name:`` (optional, defaults to ``""``), ``cols:``/``rows:``
    (optional, default 80x24), ``steps:`` — a non-empty list of mappings,
    each carrying a ``type:`` naming one of :data:`_REQUIRED_FIELDS`'s keys
    plus that type's own fields.

    Raises :class:`TuiPtySpecError` — never returns a partially-parsed
    spec — for: invalid YAML, a non-mapping document, a missing/empty/
    non-list ``steps:``, a step that isn't a mapping, an unknown ``type:``,
    a step missing one of its type's required fields, an ``expect_within``
    with an empty ``text:``, an ``expect_screen`` with neither ``text:``
    nor ``attr:`` (it would have nothing to assert and could never fail),
    or a ``click``/``expect_screen`` (via ``attr:``) naming an unrecognized
    ``button:``.
    """
    try:
        raw = yaml.safe_load(yaml_text)
    except yaml.YAMLError as e:
        raise TuiPtySpecError(f"smoke spec is not valid YAML: {e}") from e

    if not isinstance(raw, dict):
        raise TuiPtySpecError("smoke spec must be a YAML mapping at the top level")

    steps_raw = raw.get("steps")
    if not isinstance(steps_raw, list) or not steps_raw:
        raise TuiPtySpecError("smoke spec must have a non-empty 'steps:' list")

    steps: list[SmokeStep] = []
    for i, entry in enumerate(steps_raw):
        if not isinstance(entry, dict):
            raise TuiPtySpecError(f"steps[{i}] must be a mapping")
        kind = entry.get("type")
        if kind not in _REQUIRED_FIELDS:
            raise TuiPtySpecError(
                f"steps[{i}]: unknown step type {kind!r} — expected one of "
                f"{', '.join(sorted(_REQUIRED_FIELDS))}"
            )
        missing = [f for f in _REQUIRED_FIELDS[kind] if entry.get(f) in (None, "")]
        if missing:
            raise TuiPtySpecError(
                f"steps[{i}] (type={kind!r}) is missing required field(s): "
                f"{', '.join(missing)}"
            )
        button = str(entry.get("button", "left"))
        if kind == "click" and button not in _VALID_BUTTONS:
            raise TuiPtySpecError(
                f"steps[{i}]: unrecognized button {button!r} — expected one "
                f"of {', '.join(_VALID_BUTTONS)}"
            )
        region = entry.get("region")
        if region is not None and not isinstance(region, dict):
            raise TuiPtySpecError(f"steps[{i}].region must be a mapping")
        attr = entry.get("attr")
        if attr is not None and not isinstance(attr, dict):
            raise TuiPtySpecError(f"steps[{i}].attr must be a mapping")
        if kind == "expect_screen" and not entry.get("text") and not attr:
            # Neither alternative supplied means the step body
            # (`_do_expect_screen`) has nothing to check against and would
            # silently always pass — a gate that can never fail (#2096).
            # Checked after the region/attr *shape* checks above so a
            # malformed `region:`/`attr:` still reports that specific
            # problem rather than being masked by this one.
            raise TuiPtySpecError(
                f"steps[{i}] (type='expect_screen') must supply 'text:' "
                f"and/or 'attr:' — otherwise it has nothing to assert and "
                f"can never fail"
            )

        steps.append(SmokeStep(
            kind=kind,
            index=i,
            id=str(entry.get("id", "") or ""),
            key=str(entry.get("key", "") or ""),
            row=_int_default(entry.get("row"), 0),
            col=_int_default(entry.get("col"), 0),
            button=button,
            ms=_int_default(entry.get("ms"), 200),
            timeout_ms=_int_default(entry.get("timeout_ms"), 5000),
            seconds=_float_default(entry.get("seconds"), 1.0),
            text=str(entry.get("text", "") or ""),
            region=region,
            attr=attr,
        ))

    return SmokeSpec(
        name=str(raw.get("name", "") or ""),
        cols=int(raw.get("cols", 80) or 80),
        rows=int(raw.get("rows", 24) or 24),
        steps=tuple(steps),
    )


# ── raw terminal-byte encoding ──────────────────────────────────────────────

_F_KEYS = {
    "f1": b"\x1bOP", "f2": b"\x1bOQ", "f3": b"\x1bOR", "f4": b"\x1bOS",
    "f5": b"\x1b[15~", "f6": b"\x1b[17~", "f7": b"\x1b[18~", "f8": b"\x1b[19~",
    "f9": b"\x1b[20~", "f10": b"\x1b[21~", "f11": b"\x1b[23~", "f12": b"\x1b[24~",
}

_NAMED_KEYS = {
    "enter": b"\r", "return": b"\r",
    "esc": b"\x1b", "escape": b"\x1b",
    "tab": b"\t",
    "backspace": b"\x7f",
    "space": b" ",
    "up": b"\x1b[A", "down": b"\x1b[B", "right": b"\x1b[C", "left": b"\x1b[D",
    "home": b"\x1b[H", "end": b"\x1b[F",
    "pageup": b"\x1b[5~", "pagedown": b"\x1b[6~",
    "delete": b"\x1b[3~", "insert": b"\x1b[2~",
    **_F_KEYS,
}

_CTRL_KEY_RE = re.compile(r"ctrl\+([a-z])")


def encode_key(key: str) -> bytes:
    """Encode one spec ``key:`` name into the raw bytes a real terminal
    would send for it.

    Named keys (:data:`_NAMED_KEYS`) and ``ctrl+<letter>`` (control-code
    ``chr(ord(letter) - ord('a') + 1)``) are recognized case-insensitively;
    any other single character is sent as its own UTF-8 encoding. Raises
    :class:`TuiPtySpecError` for anything else (an empty string, a
    multi-character name that isn't a recognized named key).
    """
    lowered = key.lower()
    if lowered in _NAMED_KEYS:
        return _NAMED_KEYS[lowered]
    m = _CTRL_KEY_RE.fullmatch(lowered)
    if m:
        return bytes([ord(m.group(1)) - ord("a") + 1])
    if len(key) == 1:
        return key.encode("utf-8")
    raise TuiPtySpecError(f"unrecognized key {key!r}")


# SGR extended mouse-reporting protocol (`ESC [ < Cb ; Cx ; Cy M` for
# press/wheel, `... m` for release) — 1-indexed coordinates, hence the +1
# below on this module's 0-indexed `row`/`col`.
_BUTTON_CODES = {"left": 0, "middle": 1, "right": 2, "wheel-up": 64, "wheel-down": 65}
_WHEEL_BUTTONS = ("wheel-up", "wheel-down")


def encode_click(row: int, col: int, button: str = "left") -> bytes:
    """Encode a mouse click at 0-indexed ``(row, col)`` as an SGR mouse
    sequence.

    ``button`` is ``left``/``middle``/``right`` (press then release —
    ``M``/``m``) or ``wheel-up``/``wheel-down`` (a single-shot ``M`` event
    only, matching a real scroll wheel's single notch report). Raises
    :class:`TuiPtySpecError` for an unrecognized *button*.
    """
    if button not in _BUTTON_CODES:
        raise TuiPtySpecError(
            f"unrecognized mouse button {button!r} — expected one of "
            f"{', '.join(_VALID_BUTTONS)}"
        )
    code = _BUTTON_CODES[button]
    x, y = col + 1, row + 1
    press = f"\x1b[<{code};{x};{y}M".encode("ascii")
    if button in _WHEEL_BUTTONS:
        return press
    release = f"\x1b[<{code};{x};{y}m".encode("ascii")
    return press + release


# ── VT screen ────────────────────────────────────────────────────────────────

def _import_pyte():
    try:
        import pyte  # noqa: PLC0415
    except ModuleNotFoundError as exc:
        raise TuiPtyRuntimeError(
            "tui-pty needs the 'tui-pty' extra, which is not installed "
            "(missing 'pyte').\n"
            "  Install it with:  pip install 'code-coordinator[tui-pty]'"
        ) from exc
    return pyte


def _region_bounds(region: dict | None, total_rows: int, total_cols: int) -> tuple[int, int, int, int]:
    if not region:
        return 0, 0, total_rows, total_cols
    row0 = int(region.get("row", 0))
    col0 = int(region.get("col", 0))
    height = int(region.get("height", max(total_rows - row0, 0)))
    width = int(region.get("width", max(total_cols - col0, 0)))
    return row0, col0, height, width


class VtScreen:
    """A VT100/xterm screen fed the child's raw output byte stream, via
    `pyte` (the ``tui-pty`` extra) — this module never reimplements a
    terminal emulator from scratch, it reads one.
    """

    def __init__(self, cols: int, rows: int) -> None:
        pyte = _import_pyte()
        self._screen = pyte.Screen(cols, rows)
        self._stream = pyte.ByteStream(self._screen)

    def feed(self, data: bytes) -> None:
        self._stream.feed(data)

    def text(self, region: dict | None = None) -> str:
        """The rendered lines within *region* (or the whole screen when
        ``None``), one screen row per output line."""
        lines = self._screen.display
        total_rows = len(lines)
        total_cols = len(lines[0]) if lines else 0
        row0, col0, height, width = _region_bounds(region, total_rows, total_cols)
        return "\n".join(
            line[col0:col0 + width] for line in lines[row0:row0 + height]
        )

    def cell_attr(self, row: int, col: int, attr: str):
        """One SGR/text attribute (``bold``, ``italics``, ``underscore``,
        ``strikethrough``, ``reverse``, ``fg``, ``bg``, ...) of the pyte
        ``Char`` at ``(row, col)``."""
        char = self._screen.buffer[row][col]
        return getattr(char, attr)

    def cursor(self) -> tuple[int, int]:
        """The current cursor position as ``(row, col)``, 0-indexed."""
        cursor = self._screen.cursor
        return cursor.y, cursor.x


# ── pty/ConPTY child process ────────────────────────────────────────────────

class PtyChild(Protocol):
    """The minimal interface :class:`SmokeRunner` drives a child process
    through — implemented for real by :class:`UnixPtyChild` /
    :class:`WindowsConPtyChild`, and by a scripted fake in this module's
    unit tests (``tests/test_tui_pty_driver.py``)."""

    def write(self, data: bytes) -> None: ...

    def read(self, timeout: float) -> bytes:
        """Return whatever output bytes are available within *timeout*
        seconds, or ``b""`` if none arrived (never blocks past *timeout*)."""
        ...

    def is_alive(self) -> bool: ...

    def close(self) -> None: ...


class UnixPtyChild:
    """A real Unix pty running *command* under a real child process (#3483)
    — not an in-process harness. Requires a POSIX platform (:mod:`pty` is
    POSIX-only in the standard library)."""

    def __init__(self, command: str, cwd: str, cols: int, rows: int) -> None:
        if os.name != "posix":
            raise TuiPtyRuntimeError(
                "UnixPtyChild requires a POSIX platform — use "
                "WindowsConPtyChild on Windows"
            )
        import fcntl  # noqa: PLC0415
        import pty  # noqa: PLC0415
        import struct  # noqa: PLC0415
        import termios  # noqa: PLC0415

        master_fd, slave_fd = pty.openpty()
        fcntl.ioctl(slave_fd, termios.TIOCSWINSZ, struct.pack("HHHH", rows, cols, 0, 0))
        try:
            self._proc = subprocess.Popen(
                command, shell=True, cwd=cwd or None,
                stdin=slave_fd, stdout=slave_fd, stderr=slave_fd,
                preexec_fn=os.setsid, close_fds=True,
            )
        finally:
            os.close(slave_fd)
        self._master_fd = master_fd
        os.set_blocking(self._master_fd, False)
        self._closed = False

    def write(self, data: bytes) -> None:
        os.write(self._master_fd, data)

    def read(self, timeout: float) -> bytes:
        import select  # noqa: PLC0415

        ready, _, _ = select.select([self._master_fd], [], [], timeout)
        if not ready:
            return b""
        try:
            return os.read(self._master_fd, 65536)
        except OSError:
            return b""

    def is_alive(self) -> bool:
        return self._proc.poll() is None

    def close(self) -> None:
        if self._closed:
            return
        self._closed = True
        if self._proc.poll() is None:
            self._proc.terminate()
            try:
                self._proc.wait(timeout=3)
            except subprocess.TimeoutExpired:
                self._proc.kill()
        try:
            os.close(self._master_fd)
        except OSError:
            pass


class WindowsConPtyChild:
    """A real Windows ConPTY session running *command* (#3483), via the
    optional ``pywinpty`` package (the ``tui-pty`` extra's Windows-only
    dependency).

    A background reader thread continuously drains ``pywinpty``'s own
    (blocking) ``read()`` into a queue, so :meth:`read` can honor the same
    "never block past *timeout*" contract :class:`UnixPtyChild` does without
    spawning a new thread per call.
    """

    def __init__(self, command: str, cwd: str, cols: int, rows: int) -> None:
        try:
            from winpty import PtyProcess  # noqa: PLC0415
        except ModuleNotFoundError as exc:
            raise TuiPtyRuntimeError(
                "tui-pty on Windows needs the 'tui-pty' extra, which is not "
                "installed (missing 'pywinpty').\n"
                "  Install it with:  pip install 'code-coordinator[tui-pty]'"
            ) from exc

        self._proc = PtyProcess.spawn(command, cwd=cwd or None, dimensions=(rows, cols))
        self._chunks: "queue.Queue[bytes]" = queue.Queue()
        self._reader_thread = threading.Thread(target=self._read_loop, daemon=True)
        self._reader_thread.start()

    def _read_loop(self) -> None:
        while True:
            try:
                chunk = self._proc.read(65536)
            except Exception:  # noqa: BLE001 — pywinpty raises on EOF/close
                return
            if not chunk:
                return
            data = chunk.encode("utf-8", errors="replace") if isinstance(chunk, str) else chunk
            self._chunks.put(data)

    def write(self, data: bytes) -> None:
        self._proc.write(data.decode("utf-8", errors="replace"))

    def read(self, timeout: float) -> bytes:
        try:
            return self._chunks.get(timeout=timeout)
        except queue.Empty:
            return b""

    def is_alive(self) -> bool:
        return bool(self._proc.isalive())

    def close(self) -> None:
        try:
            self._proc.close(force=True)
        except Exception:  # noqa: BLE001
            pass


# ── smoke-spec runner ───────────────────────────────────────────────────────

_CPR_QUERY = b"\x1b[6n"
_READ_POLL_S = 0.05


class SmokeRunner:
    """Drives one :class:`SmokeSpec` against a real :class:`PtyChild`,
    producing coord's normalized ``{"id", "status", "message"}`` verdict
    list — the same shape :func:`coord.acceptance_drivers.parse_test_output`
    already produces for ``tui-tuidriver``.

    ``spawn_child`` is injected (not hardcoded to Unix/Windows) so unit
    tests can drive this against a scripted :class:`PtyChild` fake without
    a real terminal — see ``tests/test_tui_pty_driver.py``.
    """

    def __init__(
        self, spawn_child: Callable[[int, int], PtyChild], *, deadline: float | None = None,
    ) -> None:
        self._spawn_child = spawn_child
        self._deadline = deadline  # a `time.monotonic()` value, or None for no overall cap
        self._child: PtyChild | None = None
        self._screen: VtScreen | None = None
        self._cols = 0
        self._rows = 0
        self._lock = threading.Lock()
        self._total_bytes = 0
        self._last_byte_time = 0.0
        self._stop = threading.Event()
        self._cpr_queue: "queue.Queue[bytes]" = queue.Queue()
        self._reader_thread: threading.Thread | None = None
        self._responder_thread: threading.Thread | None = None

    def run(self, spec: SmokeSpec) -> list[dict]:
        self._cols, self._rows = spec.cols, spec.rows
        results: list[dict] = []
        try:
            for step in spec.steps:
                if self._deadline is not None and time.monotonic() >= self._deadline:
                    # The driver-level `timeout:` was exhausted by earlier
                    # steps (each of which has its own bounded per-step
                    # budget, but their sum can still exceed it) — fail the
                    # remaining steps explicitly rather than silently
                    # truncating the report, or worse, blocking past it.
                    results.append({
                        "id": step.step_id, "status": "fail",
                        "message": "aborted: tui-pty driver-level timeout exceeded",
                    })
                    continue
                results.append(self._run_step(step))
        finally:
            self._teardown()
        return results

    def _run_step(self, step: SmokeStep) -> dict:
        handlers = {
            "launch": self._do_launch,
            "key": self._do_key,
            "click": self._do_click,
            "wait_idle": self._do_wait_idle,
            "expect_screen": self._do_expect_screen,
            "expect_silent": self._do_expect_silent,
            "expect_within": self._do_expect_within,
        }
        try:
            handlers[step.kind](step)
        except (TuiPtySpecError, TuiPtyRuntimeError, AssertionError) as e:
            return {"id": step.step_id, "status": "fail", "message": str(e)}
        return {"id": step.step_id, "status": "pass", "message": ""}

    # -- action steps --

    def _do_launch(self, step: SmokeStep) -> None:
        self._child = self._spawn_child(self._cols, self._rows)
        self._screen = VtScreen(self._cols, self._rows)
        self._stop.clear()
        with self._lock:
            # Idle timing is measured from "since the last byte arrived (or
            # since launch, if none has yet)" — not from the process epoch,
            # which would otherwise read as "already idle" the instant any
            # step runs, regardless of whether the app has settled.
            self._last_byte_time = time.monotonic()
        self._reader_thread = threading.Thread(target=self._reader_loop, daemon=True)
        self._responder_thread = threading.Thread(target=self._responder_loop, daemon=True)
        self._reader_thread.start()
        self._responder_thread.start()
        # A brief startup grace window — a binary that fails to exec at all
        # (bad path, missing binary) dies near-instantly; catch that here
        # with an actionable message rather than letting every later step
        # fail against a dead child with no context.
        time.sleep(0.2)
        if not self._child.is_alive():
            raise TuiPtyRuntimeError(
                "child process exited immediately after launch (command "
                "failed to start?)"
            )

    def _require_child(self) -> PtyChild:
        if self._child is None:
            raise TuiPtyRuntimeError("no child process — spec has no 'launch' step before this one")
        return self._child

    def _do_key(self, step: SmokeStep) -> None:
        self._require_child().write(encode_key(step.key))

    def _do_click(self, step: SmokeStep) -> None:
        self._require_child().write(encode_click(step.row, step.col, step.button))

    def _do_wait_idle(self, step: SmokeStep) -> None:
        idle_for = step.ms / 1000
        deadline = time.monotonic() + step.timeout_ms / 1000
        while True:
            with self._lock:
                since = time.monotonic() - self._last_byte_time
            if since >= idle_for:
                return
            if time.monotonic() >= deadline:
                raise TuiPtyRuntimeError(
                    f"stream never went idle for {step.ms}ms within "
                    f"{step.timeout_ms}ms"
                )
            time.sleep(min(0.02, idle_for))

    # -- assertion steps --

    def _do_expect_screen(self, step: SmokeStep) -> None:
        assert self._screen is not None
        # Guarded by the same lock protecting `_total_bytes`/
        # `_last_byte_time`: `_reader_loop` mutates `self._screen` from a
        # background thread via `feed()`, so an unguarded read here could
        # race a `feed()` still applying an escape sequence.
        with self._lock:
            screen_text = self._screen.text(step.region)
            attr_failure = None
            if step.attr:
                row = int(step.attr.get("row", 0))
                col = int(step.attr.get("col", 0))
                for key, expected in step.attr.items():
                    if key in ("row", "col"):
                        continue
                    actual = self._screen.cell_attr(row, col, key)
                    if actual != expected:
                        attr_failure = (row, col, key, expected, actual)
                        break
        if step.text and step.text not in screen_text:
            region_note = f" in region {step.region}" if step.region else ""
            raise AssertionError(
                f"expected screen text {step.text!r} not found{region_note}; "
                f"screen was:\n{screen_text}"
            )
        if attr_failure is not None:
            row, col, key, expected, actual = attr_failure
            raise AssertionError(
                f"expected cell ({row},{col}).{key} == {expected!r}, "
                f"got {actual!r}"
            )

    def _do_expect_silent(self, step: SmokeStep) -> None:
        """#2096: this can only be answered by actually observing the
        window elapse and re-reading the byte counter afterward — the mere
        absence of an exception during the sleep proves nothing (nothing
        here *can* raise mid-sleep). vimcode#1634's regression: a real ~1
        Hz flicker delivers bytes at roughly 1-second intervals, so a
        window of even a couple of seconds reliably observes at least one."""
        with self._lock:
            before = self._total_bytes
        time.sleep(step.seconds)
        with self._lock:
            after = self._total_bytes
        if after != before:
            raise AssertionError(
                f"expected silence for {step.seconds}s but received "
                f"{after - before} byte(s) of output during the window"
            )

    def _do_expect_within(self, step: SmokeStep) -> None:
        assert self._screen is not None
        deadline = time.monotonic() + step.ms / 1000
        while True:
            with self._lock:
                screen_text = self._screen.text(step.region)
            if step.text in screen_text:
                return
            if time.monotonic() >= deadline:
                raise AssertionError(
                    f"expected {step.text!r} to appear within {step.ms}ms; "
                    f"screen was:\n{screen_text}"
                )
            time.sleep(0.02)

    # -- background threads --

    def _reader_loop(self) -> None:
        child = self._child
        screen = self._screen
        assert child is not None and screen is not None
        while not self._stop.is_set():
            data = child.read(_READ_POLL_S)
            if not data:
                if not child.is_alive():
                    return
                continue
            with self._lock:
                self._total_bytes += len(data)
                self._last_byte_time = time.monotonic()
                # `feed()` mutates the screen and `cursor()` reads it back —
                # both under the same lock the assertion steps take before
                # their own `text()`/`cell_attr()` reads, so neither can
                # observe a `VtScreen` mid-mutation.
                screen.feed(data)
                if _CPR_QUERY in data:
                    row, col = screen.cursor()
            if _CPR_QUERY in data:
                # Reply enqueued here, WRITTEN from `_responder_loop` — never
                # write the child's stdin synchronously from this thread.
                # See this module's docstring: doing so deadlocks a real
                # Windows ConPTY session.
                self._cpr_queue.put(f"\x1b[{row + 1};{col + 1}R".encode("ascii"))

    def _responder_loop(self) -> None:
        while not self._stop.is_set():
            try:
                reply = self._cpr_queue.get(timeout=0.1)
            except queue.Empty:
                continue
            child = self._child
            if child is None:
                return
            try:
                child.write(reply)
            except Exception:  # noqa: BLE001 — child may have exited underneath us
                return

    def _teardown(self) -> None:
        self._stop.set()
        for t in (self._reader_thread, self._responder_thread):
            if t is not None:
                t.join(timeout=2)
        if self._child is not None:
            self._child.close()


def spawn_real_pty(command: str, cwd: str, cols: int, rows: int) -> PtyChild:
    """The default ``spawn_child`` for :func:`run_smoke_spec`: a real
    :class:`UnixPtyChild` on POSIX, a real :class:`WindowsConPtyChild` on
    Windows."""
    if os.name == "nt":
        return WindowsConPtyChild(command, cwd, cols, rows)
    return UnixPtyChild(command, cwd, cols, rows)


def run_smoke_spec(
    spec_text: str, *, launch_command: str, cwd: str,
    spawn_child: Callable[[int, int], PtyChild] | None = None,
    timeout: float | None = None,
) -> list[dict]:
    """Parse *spec_text* and run it against a real pty/ConPTY launching
    *launch_command* in *cwd* — the top-level entry point
    :func:`coord.acceptance_drivers._run_tui_pty` calls.

    *spawn_child*, when given, overrides how the child process is spawned
    (used by tests to inject a scripted fake — see
    ``tests/test_tui_pty_driver.py``); defaults to :func:`spawn_real_pty`.

    *timeout*, when given, is an overall wall-clock budget in seconds for
    the whole spec (mirrors every other driver kind's own ``timeout:``).
    Each step already carries its own bounded budget (``ms``/``seconds``/
    ``timeout_ms``), but their sum can still exceed *timeout*; once it's
    exhausted, :meth:`SmokeRunner.run` fails every remaining step
    explicitly rather than truncating the report or blocking past it.

    Raises :class:`TuiPtySpecError` for a malformed spec. Runtime failures
    (the child dies, a step times out, an assertion fails) do NOT raise —
    they're folded into the returned list as a ``status="fail"`` entry, the
    same "partial results, not a crash" contract
    :func:`coord.acceptance_drivers.parse_test_output` already gives
    ``tui-tuidriver``.
    """
    spec = parse_smoke_spec(spec_text)

    def _spawn(cols: int, rows: int) -> PtyChild:
        if spawn_child is not None:
            return spawn_child(cols, rows)
        return spawn_real_pty(launch_command, cwd, cols, rows)

    deadline = time.monotonic() + timeout if timeout is not None else None
    runner = SmokeRunner(_spawn, deadline=deadline)
    return runner.run(spec)
